In [1]:
import bs4 as bs
import urllib.request
import pandas as pd
import pycountry
import pycountry_convert as pc
import numpy as np

# Liste des joueurs FR

In [142]:
# SIMPLE HOMME

url = "https://bwf.tournamentsoftware.com/ranking/category.aspx?id=33633&category=472&ps=100&C472FOC=&order=12&p=10"

source = urllib.request.urlopen(url).read()
soup = bs.BeautifulSoup(source,'lxml')

table = soup.find('table', attrs={'class':'ruler'})
table_rows = table.find_all('tr')

france_ranking = []

for tr in table_rows:
    cols = tr.find_all('td')
    if len(cols) >= 4 and "FRA" in cols[3].text:
        #0:rank, 1: previous rank, 3: country 3 letters, 4: player, 6: memberId, 7: Points, 8: Tournaments, 9: Confederation, 10: country
        try:
            previous_rank = cols[1].get('title').split('Previous rank: ')[1]
        except:
            previous_rank = None
        link = cols[4].find('a').get('href')
        france_ranking.append([cols[0].text,previous_rank,cols[3].text,cols[4].text.split('] ')[1],cols[6].text,cols[7].text,cols[8].text,cols[9].text,cols[10].text,link.split('&player=')[1]])
        
        
df_france_ranking = pd.DataFrame(france_ranking,columns=['Rank','Previous Rank','Short Country','Player','MemberId','Points','Tournaments','Confederation','Country','PlayerId'])

df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('int')
df_france_ranking = df_france_ranking.sort_values(by=['Rank'], ascending=True)
df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('str')
df_france_ranking.reset_index(drop=True,inplace=True)

df_france_ranking.to_excel('MEN_SINGLES_FRANCE_PLAYERS.xlsx',index=False)

df_france_ranking.head(5)

,Rank,Previous Rank,Short Country,Player,MemberId,Points,Tournaments,Confederation,Country,PlayerId
0,25,25,FRA,Toma Junior POPOV,61628,43913,17,Europe,France,674117
1,40,40,FRA,Brice LEVERDEZ,52968,29820,12,Europe,France,108274
2,41,41,FRA,Christo POPOV,72885,28950,13,Europe,France,1995693
3,45,45,FRA,Arnaud MERKLE,59543,27243,12,Europe,France,1355035
4,68,68,FRA,Alex LANIER,94580,21145,12,Europe,France,2017832

In [143]:
# SIMPLE FEMME

url = "https://bwf.tournamentsoftware.com/ranking/category.aspx?id=33731&category=473&ogid=0F8E17C1-FC1A-4584-A61E-40A81EFD2F11&C473FOC=&p=1&ps=100"

source = urllib.request.urlopen(url).read()
soup = bs.BeautifulSoup(source,'lxml')

table = soup.find('table', attrs={'class':'ruler'})
table_rows = table.find_all('tr')

france_ranking = []

for tr in table_rows:
    cols = tr.find_all('td')
    if len(cols) >= 4 and "FRA" in cols[3].text:
        #0:rank, 1: previous rank, 3: country 3 letters, 4: player, 6: memberId, 7: Points, 8: Tournaments, 9: Confederation, 10: country
        try:
            previous_rank = cols[1].get('title').split('Previous rank: ')[1]
        except:
            previous_rank = None
        link = cols[4].find('a').get('href')
        france_ranking.append([cols[0].text,previous_rank,cols[3].text,cols[4].text.split('] ')[1],cols[6].text,cols[7].text,cols[8].text,cols[9].text,cols[10].text,link.split('&player=')[1]])
        
        
df_france_ranking = pd.DataFrame(france_ranking,columns=['Rank','Previous Rank','Short Country','Player','MemberId','Points','Tournaments','Confederation','Country','PlayerId'])

df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('int')
df_france_ranking = df_france_ranking.sort_values(by=['Rank'], ascending=True)
df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('str')
df_france_ranking.reset_index(drop=True,inplace=True)

df_france_ranking.to_excel('WOMEN_SINGLES_FRANCE_PLAYERS.xlsx',index=False)

df_france_ranking.head(5)

,Rank,Previous Rank,Short Country,Player,MemberId,Points,Tournaments,Confederation,Country,PlayerId
0,40,44,FRA,QI Xuefei,77256,30690,14,Europe,France,143810
1,50,50,FRA,LÃ©Onice HUET,88582,26712,16,Europe,France,1725868
2,64,64,FRA,Yaelle HOYAUX,82409,19195,14,Europe,France,454429
3,153,172,FRA,Rosy Oktavia PANCASARI,65540,8780,11,Europe,France,353124
4,166,164,FRA,Malya HOAREAU,71108,8010,9,Europe,France,4253369

In [144]:
# Double Hommes

url = "https://bwf.tournamentsoftware.com/ranking/category.aspx?id=33731&category=474&ogid=0F8E17C1-FC1A-4584-A61E-40A81EFD2F11&C474FOC=&p=1&ps=100"

source = urllib.request.urlopen(url).read()
soup = bs.BeautifulSoup(source,'lxml')

table = soup.find('table', attrs={'class':'ruler'})
table_rows = table.find_all('tr')

france_ranking = []

for tr in table_rows:
    cols = tr.find_all('td')
    
    if len(cols) >= 4 and "FRA" in cols[3].text:
        #0:rank, 1: previous rank, 3: country 3 letters, 4: player, 6: memberId, 7: Points, 8: Tournaments, 9: Confederation, 10: country
        try:
            previous_rank = cols[1].get('title').split('Previous rank: ')[1]
        except:
            previous_rank = None
            
        link_players_id = cols[4].find_all('a')
        link_players_id[0]=link_players_id[0].get('href')
        link_players_id[1]=link_players_id[1].get('href')
        
        players_list = cols[4].text.split('[FRA] ')
        
        members_id_list = cols[6].get_text(',').split(',')
        if len(players_list)>2:
            france_ranking.append([cols[0].text,previous_rank,cols[3].get_text(',').split(',')[0],players_list[1],players_list[2],members_id_list[0],members_id_list[1],cols[7].text,cols[8].text,cols[9].text,cols[10].text,link_players_id[0].split('&player=')[1],link_players_id[1].split('&player=')[1]])
        
        
df_france_ranking = pd.DataFrame(france_ranking,columns=['Rank','Previous Rank','Short Country','Player1','Player2','MemberId1','MemberId2','Points','Tournaments','Confederation','Country','PlayerId1','PlayerId2'])

df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('int')
df_france_ranking = df_france_ranking.sort_values(by=['Rank'], ascending=True)
df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('str')
df_france_ranking.reset_index(drop=True,inplace=True)

df_france_ranking.to_excel('MEN_DOUBLES_FRANCE_PLAYERS.xlsx',index=False)

df_france_ranking.head(5)

,Rank,Previous Rank,Short Country,Player1,Player2,MemberId1,MemberId2,Points,Tournaments,Confederation,Country,PlayerId1,PlayerId2
0,33,33,FRA,Christo POPOV,Toma Junior POPOV,72885,61628,34788,18,Europe,France,1995693,674117
1,36,36,FRA,Lucas CORVEE,Ronan LABAR,89416,22038,32069,18,Europe,France,197408,108392
2,48,44,FRA,Fabien DELRUE,William VILLEGER,91739,88264,25545,8,Europe,France,1725909,1995906
3,79,87,FRA,Julien MAIO,William VILLEGER,73323,88264,15420,7,Europe,France,300576,1995906
4,90,89,FRA,Kenji LOVANG,Leo ROSSI,62969,96690,12810,13,Europe,France,2026221,393198

In [145]:
# Double Femmes

url = "https://bwf.tournamentsoftware.com/ranking/category.aspx?id=33731&category=475&ogid=0F8E17C1-FC1A-4584-A61E-40A81EFD2F11&C475FOC=&p=1&ps=100"

source = urllib.request.urlopen(url).read()
soup = bs.BeautifulSoup(source,'lxml')

table = soup.find('table', attrs={'class':'ruler'})
table_rows = table.find_all('tr')

france_ranking = []

for tr in table_rows:
    cols = tr.find_all('td')
    
    if len(cols) >= 4 and "FRA" in cols[3].text:
        #0:rank, 1: previous rank, 3: country 3 letters, 4: player, 6: memberId, 7: Points, 8: Tournaments, 9: Confederation, 10: country
        try:
            previous_rank = cols[1].get('title').split('Previous rank: ')[1]
        except:
            previous_rank = None
            
        link_players_id = cols[4].find_all('a')
        link_players_id[0]=link_players_id[0].get('href')
        link_players_id[1]=link_players_id[1].get('href')
        
        players_list = cols[4].text.split('[FRA] ')
        
        members_id_list = cols[6].get_text(',').split(',')
        if len(players_list)>2:
            france_ranking.append([cols[0].text,previous_rank,cols[3].get_text(',').split(',')[0],players_list[1],players_list[2],members_id_list[0],members_id_list[1],cols[7].text,cols[8].text,cols[9].text,cols[10].text,link_players_id[0].split('&player=')[1],link_players_id[1].split('&player=')[1]])
        
        
df_france_ranking = pd.DataFrame(france_ranking,columns=['Rank','Previous Rank','Short Country','Player1','Player2','MemberId1','MemberId2','Points','Tournaments','Confederation','Country','PlayerId1','PlayerId2'])

df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('int')
df_france_ranking = df_france_ranking.sort_values(by=['Rank'], ascending=True)
df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('str')
df_france_ranking.reset_index(drop=True,inplace=True)

df_france_ranking.to_excel('WOMEN_DOUBLES_FRANCE_PLAYERS.xlsx',index=False)

df_france_ranking.head(5)

,Rank,Previous Rank,Short Country,Player1,Player2,MemberId1,MemberId2,Points,Tournaments,Confederation,Country,PlayerId1,PlayerId2
0,31,30,FRA,Margot LAMBERT,Anne TRAN,99891,98854,36014,18,Europe,France,1355183,356059
1,65,63,FRA,Flavie VALLET,Emilie VERCELOT,63229,72254,18335,12,Europe,France,2406661,2018301
2,234,235,FRA,Romane CLOTEAUX-FOUCAULT,Anouk NAMBOT,78135,89788,3360,4,Europe,France,2026147,3491931
3,251,255,FRA,Tea MARGUERITTE,Camille POGNANTE,73899,84050,3040,3,Europe,France,2870940,3489805
4,264,201,FRA,Tea MARGUERITTE,Anna TATRANOVA,73899,71285,2960,2,Europe,France,2870940,2018084

In [146]:
# Double Mixte

url = "https://bwf.tournamentsoftware.com/ranking/category.aspx?id=33731&category=476&ogid=0F8E17C1-FC1A-4584-A61E-40A81EFD2F11&C476FOC=&p=1&ps=100"

source = urllib.request.urlopen(url).read()
soup = bs.BeautifulSoup(source,'lxml')

table = soup.find('table', attrs={'class':'ruler'})
table_rows = table.find_all('tr')

france_ranking = []

for tr in table_rows:
    cols = tr.find_all('td')
    if len(cols) >= 4 and "FRA" in cols[3].text:
        #0:rank, 1: previous rank, 3: country 3 letters, 4: player, 6: memberId, 7: Points, 8: Tournaments, 9: Confederation, 10: country
        try:
            previous_rank = cols[1].get('title').split('Previous rank: ')[1]
        except:
            previous_rank = None
            
        link_players_id = cols[4].find_all('a')
        link_players_id[0]=link_players_id[0].get('href')
        link_players_id[1]=link_players_id[1].get('href')
        
        players_list = cols[4].text.split('[FRA] ')
        
        members_id_list = cols[6].get_text(',').split(',')
        if len(players_list)>2:
            france_ranking.append([cols[0].text,previous_rank,cols[3].get_text(',').split(',')[0],players_list[1],players_list[2],members_id_list[0],members_id_list[1],cols[7].text,cols[8].text,cols[9].text,cols[10].text,link_players_id[0].split('&player=')[1],link_players_id[1].split('&player=')[1]])
            
        
df_france_ranking = pd.DataFrame(france_ranking,columns=['Rank','Previous Rank','Short Country','Player1','Player2','MemberId1','MemberId2','Points','Tournaments','Confederation','Country','PlayerId1','PlayerId2'])

df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('int')
df_france_ranking = df_france_ranking.sort_values(by=['Rank'], ascending=True)
df_france_ranking['Rank'] = df_france_ranking['Rank'].astype('str')
df_france_ranking.reset_index(drop=True,inplace=True)

df_france_ranking.to_excel('MIXED_DOUBLES_FRANCE_PLAYERS.xlsx',index=False)

df_france_ranking.head(5)

,Rank,Previous Rank,Short Country,Player1,Player2,MemberId1,MemberId2,Points,Tournaments,Confederation,Country,PlayerId1,PlayerId2
0,5,5,FRA,Thom GICQUEL,Delphine DELRUE,68544,70762,66582,16,Europe,France,1354995,674128
1,46,42,FRA,William VILLEGER,Anne TRAN,88264,98854,25430,9,Europe,France,1995906,356059
2,62,60,FRA,Lucas CORVEE,Sharone BAUER,89416,98332,19150,11,Europe,France,197408,2291359
3,106,105,FRA,Fabien DELRUE,Vimala HERIAU,91739,90317,10120,4,Europe,France,1725909,1225702
4,122,130,FRA,Enogat ROY,Anna TATRANOVA,85118,71285,8870,9,Europe,France,2875558,2018084

# Liste des tournois de l'annÃ©e

In [147]:
# Liste des 'NOCs'
url = "https://en.wikipedia.org/wiki/List_of_IOC_country_codes#Current_NOCs"
hdr = {'User-Agent': 'Mozilla/5.0'}
req = urllib.request.Request(url,headers=hdr)
source = urllib.request.urlopen(req).read()
soup = bs.BeautifulSoup(source,'lxml')

table = soup.find('table')

list_of_NOCs = []

table_rows = table.find_all('tr')
for tr in table_rows:
    cols = tr.find_all('td')
    if len(cols)>0:
        list_of_NOCs.append([cols[0].text.strip(),cols[1].text.strip()])
        
df_NOCs_list = pd.DataFrame(list_of_NOCs,columns=['Code','National Olympic Committee'])

df_NOCs_list.to_excel('NOC_COUNTRY_CODES.xlsx', index=False)

df_NOCs_list.head(5)

  Code National Olympic Committee
0  AFG                Afghanistan
1  ALB                    Albania
2  ALG                    Algeria
3  AND                    Andorra
4  ANG                     Angola

In [98]:
def country_to_continent(country_alpha3, df_NOC):
    if country_alpha3=="ENG" or country_alpha3=="SCO" or country_alpha3=="WAL":
        return 'Europe'
    elif country_alpha3=="IRI" or country_alpha3=="KOR" or country_alpha3=="TPE" or country_alpha3=="VIE" or country_alpha3=="HKG":
        return 'Asia'
    elif country_alpha3=="VEN":
        return "South America"
    else:
        country_name = df_NOC[df_NOC['Code']==country_alpha3]['National Olympic Committee'].values[0]
        country = pycountry.countries.get(name=country_name)

        country_continent_code = pc.country_alpha2_to_continent_code(country.alpha_2)
        country_continent_name = pc.convert_continent_code_to_continent_name(country_continent_code)
    
    return country_continent_name

In [100]:
url = "https://corporate.bwfbadminton.com/events/calendar/2022/all/0/-1/"
hdr = {'User-Agent': 'Mozilla/5.0'}
req = urllib.request.Request(url,headers=hdr)
source = urllib.request.urlopen(req).read()
soup = bs.BeautifulSoup(source,'lxml')

tables = soup.find_all('table')

tournaments_list = []

df_NOC = pd.read_excel('NOC_COUNTRY_CODES.xlsx')

month = 0
for table in tables:
    month+=1
    table_rows = table.find_all('tr')
    for tr in table_rows:
        cols = tr.find_all('td')
        if len(cols)>6 and not "Junior" in cols[5].text:
            # 0: Week, 1: Country, # 2: Dates, # 3: Tournament, #5: Category, # 6: City
            try:
                continent = country_to_continent(cols[1].text.strip(),df_NOC)
            except: 
                continent = None
            tournaments_list.append([str(month),cols[0].text.strip(),cols[2].text.strip(),continent,cols[1].text.strip(),cols[6].text.strip(),cols[3].text.strip(),cols[5].text.strip()])
        
df_tournaments_list = pd.DataFrame(tournaments_list,columns=['Month','Week','Dates','Continent','Country','City','Tournament','Category'])

df_tournaments_list.to_excel('2022_BWF_TOURNAMENTS_LIST.xlsx',index=False)

df_tournaments_list.head(5)

,Month,Week,Dates,Continent,Country,City,Tournament,Category
0,1,02,11 -16,Asia,IND,New Delhi,YONEX-SUNRISE India Open 2022,HSBC BWF World Tour Super 500
1,1,02,13 -16,Europe,EST,Tallinn,YONEX Estonian International 2022,International Series
2,1,03,18 -23,Asia,IND,Lucknow,Syed Modi India International 2022,HSBC BWF World Tour Super 300
3,1,03,20 -23,Europe,SWE,uppsala,VICTOR Swedish Open 2022,International Series
4,1,04,25 -30,Asia,IND,Cuttack,Odisha Open 2022,BWF Tour Super 100

In [101]:
#Liste des tournois avec les dates clÃ©s
url = "https://corporate.bwfbadminton.com/events/calendar/2022/all/0/-1/"
hdr = {'User-Agent': 'Mozilla/5.0'}
req = urllib.request.Request(url,headers=hdr)
source = urllib.request.urlopen(req).read()
soup = bs.BeautifulSoup(source,'lxml')

tables = soup.find_all('ul', attrs={'class':'list-unstyled bwf-ul'})

key_dates = [] #Entry Deadline, World Ranking Date, M & Q Report, Seeding Date, Withdrawal Deadline, Draw Date, Tournament Link, Website, Updated Date

for table in tables:
    key_dates_tournament = ["","","","","","","","",""]
    table_rows = table.find_all('li')
    for j in range(len(table_rows)):
        if "Entry Deadline" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[0]= date
        elif "World Ranking Date" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[1]= date
        elif "M & Q Report" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[2]= date
        elif "Seeding Date" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[3]= date
        elif "Withdrawal Deadline" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[4]= date
        elif "Draw Date" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[5]= date
        elif "Tournament Link" in table_rows[j].text:
            key_dates_tournament[6]= table_rows[j].find('a').get('href')
        elif "Website" in table_rows[j].text:
            key_dates_tournament[7]= table_rows[j].find('a').get('href')
        elif "Updated date" in table_rows[j].text:
            date = table_rows[j].text.split(':')[1].strip()
            key_dates_tournament[8]= date
    key_dates.append(key_dates_tournament)

df_tournaments_key_dates = pd.DataFrame(key_dates,columns=['Entry Deadline', 'World Ranking Date', 'M & Q Report', 'Seeding Date', 'Withdrawal Deadline', 'Draw Date', 'Tournament Link', 'Website', 'Updated Date'])

df_tournaments = pd.read_excel('2022_BWF_ALL_TOURNAMENTS_LIST.xlsx')

df_tournaments_key_dates = pd.concat([df_tournaments,df_tournaments_key_dates],axis=1)

df_tournaments_key_dates.to_excel('2022_BWF_ALL_TOURNAMENTS_LIST_WITH_KEY_DATES.xlsx',index=False)

df_tournaments_key_dates

,Month,Week,Dates,Continent,Country,City,Tournament,Category,Entry Deadline,World Ranking Date,M & Q Report,Seeding Date,Withdrawal Deadline,Draw Date,Tournament Link,Website,Updated Date
0,1,2,11 -16,Asia,IND,New Delhi,YONEX-SUNRISE India Open 2022,HSBC BWF World Tour Super 500,07/12/2021,07/12/2021,10/12/2021,14/12/2021,20/12/2021,21/12/2021,https://bwf.tournamentsoftware.com/sport/tourn...,,21/03/2023
1,1,2,13 -16,Europe,EST,Tallinn,YONEX Estonian International 2022,International Series,14/12/2021,,,,,,,,21/03/2023
2,1,3,18 -23,Asia,IND,Lucknow,Syed Modi India International 2022,HSBC BWF World Tour Super 300,21/12/2021,21/12/2021,24/12/2021,21/12/2021,27/12/2021,28/12/2021,https://bwf.tournamentsoftware.com/sport/tourn...,,21/03/2023
3,1,3,20 -23,Europe,SWE,uppsala,VICTOR Swedish Open 2022,International Series,21/12/2021,,,,,,,,21/03/2023
4,1,4,25 -30,Asia,IND,Cuttack,Odisha Open 2022,BWF Tour Super 100,28/12/2021,28/12/2021,31/12/2021,28/12/2021,03/01/2022,04/01/2022,https://bwf.tournamentsoftware.com/sport/tourn...,,21/03/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,12,50,13 -18,Asia,MAS,Ipoh,PETRONAS Malaysia International Challenge 2022...,International Challenge,22/11/2022,,,,,,,,21/03/2023
197,12,50,15 -18,Europe,POL,tbc,Polish U19 International 2022 (Cancelled),Junior International Series,15/11/2022,,,,,,,,21/03/2023
198,12,50,15 -18,Europe,BUL,Sofia,2023 European Mixed Team Championships - Quali...,Continental Team Championships,12/12/2022,,,,,,,,21/03/2023
199,12,50,15 -17,Africa,MRI,Rose Hill,All Africa Junior Individual Championships 2022,Continental Junior Individual Championships,15/11/2022,,,,,,,,21/03/2023
200,12,51,19 -22,Asia,TUR,Ankara,Turkey Open 2022 (Cancelled),International Series,22/11/2022,,,,,,,,21/03/2023

In [104]:
df_tournaments_key_dates = pd.read_excel('2022_BWF_ALL_TOURNAMENTS_LIST_WITH_KEY_DATES.xlsx')

df_tournaments_key_dates = df_tournaments_key_dates[~df_tournaments_key_dates['Category'].str.contains("Junior")]

df_tournaments_key_dates.reset_index(drop=True,inplace=True)

df_tournaments_distribution = pd.read_excel('2022_BWF_TOURNAMENTS_LIST_WITH_DISTRIBUTION.xlsx')

df_tournaments_distribution = df_tournaments_distribution.join(df_tournaments_key_dates.iloc[:,8:])

df_tournaments_distribution.to_excel('2022_BWF_TOURNAMENTS_LIST_WITH_DISTRIBUTION_AND_KEY_DATES.xlsx',index=False)

df_tournaments_distribution

,Month,Week,Dates,Continent,Country,City,Tournament,Category,Team,1,...,513-1024,Entry Deadline,World Ranking Date,M & Q Report,Seeding Date,Withdrawal Deadline,Draw Date,Tournament Link,Website,Updated Date
0,1,2,11 -16,Asia,IND,New Delhi,YONEX-SUNRISE India Open 2022,HSBC BWF World Tour Super 500,0,9200.0,...,40.0,07/12/2021,07/12/2021,10/12/2021,14/12/2021,20/12/2021,21/12/2021,https://bwf.tournamentsoftware.com/sport/tourn...,NaN,21/03/2023
1,1,2,13 -16,Europe,EST,Tallinn,YONEX Estonian International 2022,International Series,0,2500.0,...,10.0,14/12/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
2,1,3,18 -23,Asia,IND,Lucknow,Syed Modi India International 2022,HSBC BWF World Tour Super 300,0,7000.0,...,30.0,21/12/2021,21/12/2021,24/12/2021,21/12/2021,27/12/2021,28/12/2021,https://bwf.tournamentsoftware.com/sport/tourn...,NaN,21/03/2023
3,1,3,20 -23,Europe,SWE,uppsala,VICTOR Swedish Open 2022,International Series,0,2500.0,...,10.0,21/12/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
4,1,4,25 -30,Asia,IND,Cuttack,Odisha Open 2022,BWF Tour Super 100,0,5500.0,...,30.0,28/12/2021,28/12/2021,31/12/2021,28/12/2021,03/01/2022,04/01/2022,https://bwf.tournamentsoftware.com/sport/tourn...,NaN,21/03/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,12,49,07 -11,Asia,THA,Bangkok,HSBC BWF World Tour Finals 2022,HSBC BWF World Tour Finals,0,12000.0,...,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,12,49,08 -11,Europe,MLT,Cospicua,Malta International 2022 presented by VICTOR,Future Series,0,1700.0,...,5.0,08/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
135,12,50,13 -18,Asia,MAS,Ipoh,PETRONAS Malaysia International Challenge 2022...,International Challenge,0,4000.0,...,20.0,22/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
136,12,50,15 -18,Europe,BUL,Sofia,2023 European Mixed Team Championships - Quali...,Continental Team Championships,1,NaN,...,NaN,12/12/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
137,12,51,19 -22,Asia,TUR,Ankara,Turkey Open 2022 (Cancelled),International Series,0,2500.0,...,10.0,22/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023

# RÃ©partition des points par tournois

In [102]:
df_tournaments = pd.read_excel('2022_BWF_TOURNAMENTS_LIST.xlsx')

df_tournaments['Team']=None
df_tournaments['1']=None
df_tournaments['2']=None
df_tournaments['3']=None
df_tournaments['4']=None
df_tournaments['5-6']=None
df_tournaments['7-8']=None
df_tournaments['9-16']=None
df_tournaments['17-32']=None
df_tournaments['33-64']=None
df_tournaments['65-128']=None
df_tournaments['129-256']=None
df_tournaments['257-512']=None
df_tournaments['513-1024']=None

df_tournaments

,Month,Week,Dates,Continent,Country,City,Tournament,Category,Team,1,...,4,5-6,7-8,9-16,17-32,33-64,65-128,129-256,257-512,513-1024
0,1,2,11 -16,Asia,IND,New Delhi,YONEX-SUNRISE India Open 2022,HSBC BWF World Tour Super 500,None,None,...,None,None,None,None,None,None,None,None,None,None
1,1,2,13 -16,Europe,EST,Tallinn,YONEX Estonian International 2022,International Series,None,None,...,None,None,None,None,None,None,None,None,None,None
2,1,3,18 -23,Asia,IND,Lucknow,Syed Modi India International 2022,HSBC BWF World Tour Super 300,None,None,...,None,None,None,None,None,None,None,None,None,None
3,1,3,20 -23,Europe,SWE,uppsala,VICTOR Swedish Open 2022,International Series,None,None,...,None,None,None,None,None,None,None,None,None,None
4,1,4,25 -30,Asia,IND,Cuttack,Odisha Open 2022,BWF Tour Super 100,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,12,49,07 -11,Asia,THA,Bangkok,HSBC BWF World Tour Finals 2022,HSBC BWF World Tour Finals,None,None,...,None,None,None,None,None,None,None,None,None,None
134,12,49,08 -11,Europe,MLT,Cospicua,Malta International 2022 presented by VICTOR,Future Series,None,None,...,None,None,None,None,None,None,None,None,None,None
135,12,50,13 -18,Asia,MAS,Ipoh,PETRONAS Malaysia International Challenge 2022...,International Challenge,None,None,...,None,None,None,None,None,None,None,None,None,None
136,12,50,15 -18,Europe,BUL,Sofia,2023 European Mixed Team Championships - Quali...,Continental Team Championships,None,None,...,None,None,None,None,None,None,None,None,None,None
137,12,51,19 -22,Asia,TUR,Ankara,Turkey Open 2022 (Cancelled),International Series,None,None,...,None,None,None,None,None,None,None,None,None,None

In [103]:
df_distributions = pd.read_excel('BWF_TOURNAMENTS_POINTS_DISTRIBUTION.xlsx')

for i in range(len(df_tournaments)):
    
    #On dÃ©tecte les tournois par Ã©quipe
    if "Team" in df_tournaments['Category'].iloc[i]:
        df_tournaments.loc[i,'Team']="1"
    else:
        df_tournaments.loc[i,'Team']="0"
        
    #On fait le lien entre les deux tableaux
    if df_tournaments['Category'].iloc[i]=='HSBC BWF World Tour Finals':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Tour Finals'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='HSBC BWF World Tour Super 1000':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Tour Super 1000'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='HSBC BWF World Tour Super 750':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Tour Super 750'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='HSBC BWF World Tour Super 500':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Tour Super 500'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='HSBC BWF World Tour Super 300':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Tour Super 300'].iloc[0,3:].values
    
    elif df_tournaments['Category'].iloc[i]=='BWF Tour Super 100':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Tour Super 100'].iloc[0,3:].values
    
    elif df_tournaments['Category'].iloc[i]=='International Challenge':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='International Challenge'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='International Series':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='International Series'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='Future Series':
        df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='Future Series'].iloc[0,3:].values

    elif df_tournaments['Category'].iloc[i]=='Grade 1 - Individual Tournaments':
        if "World Championships" in df_tournaments['Tournament'].iloc[i]:
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='BWF World Championships'].iloc[0,3:].values
        elif "Olympic Games" in df_tournaments['Tournament'].iloc[i]:
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='Olympic Games'].iloc[0,3:].values
            
    elif df_tournaments['Category'].iloc[i]=='Continental Individual Games' or df_tournaments['Category'].iloc[i]=='Multi-Sport Games' or df_tournaments['Category'].iloc[i]=='Continental Individual Championships':
        continent = df_tournaments['Continent'].iloc[i]
        if continent=='Europe':
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='European Championships'].iloc[0,3:].values

        elif continent=='Asia':
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='Asian Championships'].iloc[0,3:].values

        elif continent=='Africa':
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='African Championships'].iloc[0,3:].values

        elif continent=='Oceania':
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='Oceania Championships'].iloc[0,3:].values

        elif continent=='South America' or continent=='North America':
            df_tournaments.iloc[i,9:] = df_distributions[df_distributions['Name']=='Pan American Championships'].iloc[0,3:].values

df_tournaments.to_excel('2022_BWF_TOURNAMENTS_LIST_WITH_DISTRIBUTION.xlsx',index=False)
        
df_tournaments.head(5)

,Month,Week,Dates,Continent,Country,City,Tournament,Category,Team,1,...,4,5-6,7-8,9-16,17-32,33-64,65-128,129-256,257-512,513-1024
0,1,2,11 -16,Asia,IND,New Delhi,YONEX-SUNRISE India Open 2022,HSBC BWF World Tour Super 500,0,9200,...,6420,5040,5040,3600,2220,880,430,170,80,40
1,1,2,13 -16,Europe,EST,Tallinn,YONEX Estonian International 2022,International Series,0,2500,...,1750,1370,1370,920,550,210,100,40,20,10
2,1,3,18 -23,Asia,IND,Lucknow,Syed Modi India International 2022,HSBC BWF World Tour Super 300,0,7000,...,4900,3850,3850,2750,1670,660,320,130,60,30
3,1,3,20 -23,Europe,SWE,uppsala,VICTOR Swedish Open 2022,International Series,0,2500,...,1750,1370,1370,920,550,210,100,40,20,10
4,1,4,25 -30,Asia,IND,Cuttack,Odisha Open 2022,BWF Tour Super 100,0,5500,...,3850,3030,3030,2110,1290,510,240,100,45,30

# Liste des tournois d'un joueur

In [88]:
#Simple Homme
df_french_players = pd.read_excel('./FRANCE_PLAYERS/MEN_SINGLES_FRANCE_PLAYERS.xlsx')

df_french_players = df_french_players[df_french_players['Points']>=1000]

df_french_players

,Rank,Previous Rank,Short Country,Player,MemberId,Points,Tournaments,Confederation,Country,PlayerId
0,25,25,FRA,Toma Junior POPOV,61628,43913,17,Europe,France,674117
1,40,40,FRA,Brice LEVERDEZ,52968,29820,12,Europe,France,108274
2,41,41,FRA,Christo POPOV,72885,28950,13,Europe,France,1995693
3,45,45,FRA,Arnaud MERKLE,59543,27243,12,Europe,France,1355035
4,68,68,FRA,Alex LANIER,94580,21145,12,Europe,France,2017832
5,80,80,FRA,Lucas CLAERBOUT,89506,18290,12,Europe,France,116891
6,87,87,FRA,Thomas ROUXEL,38500,17110,7,Europe,France,113724
7,139,139,FRA,Enogat ROY,85118,10340,14,Europe,France,2875558
8,167,167,FRA,Valentin SINGER,96339,8010,15,Europe,France,1451568
9,206,198,FRA,GrÃ©goire DESCHAMP,75657,6450,11,Europe,France,2018156
10,224,212,FRA,Sacha LEVEQUE,86866,5640,13,Europe,France,2018229
11,251,222,FRA,Amaury LIEVRE,68262,5130,9,Europe,France,3141994
12,285,285,FRA,Tino DAOUDAL,93913,4150,11,Europe,France,3060321
13,288,288,FRA,Martin OUAZZEN,69243,4070,11,Europe,France,2402380
14,301,302,FRA,Leo VAN GYSEL,85281,3770,8,Europe,France,2401723
15,322,322,FRA,Yanis GAUDIN,83581,3370,6,Europe,France,2018454
16,431,434,FRA,Simon BARON-VEZILIER,66522,1880,6,Europe,France,2018012
17,439,381,FRA,Rafael GAVOIS,58873,1840,7,Europe,France,2406334
18,453,455,FRA,Louis DUCROT,99461,1720,10,Europe,France,1199368
19,457,460,FRA,Thomas FOURCADE,59956,1690,6,Europe,France,2018592
20,464,456,FRA,Yohan BARBIERI,66489,1650,9,Europe,France,3326261
21,486,488,FRA,Samson GRADT-URBAN,60379,1520,1,Europe,France,387380
22,504,504,FRA,Guilhem HOYAUX,54991,1440,4,Europe,France,2402212
23,508,508,FRA,Romain FRANK,76496,1410,6,Europe,France,2442048
24,544,546,FRA,Arthur WAKHEVITSCH,66224,1220,8,Europe,France,2018553
25,563,564,FRA,Paul TOURNEFIER,89757,1090,4,Europe,France,3077833

In [89]:
#On va rÃ©cupÃ¨rer la liste des tournois des joueurs au 1er Janvier 2023
id_first_week = "32857"

for i in range(len(df_french_players)):
    playerId = df_french_players['PlayerId'].iloc[i]

    player_name = df_french_players['Player'].iloc[i]

    url_player = 'https://bwf.tournamentsoftware.com/ranking/player.aspx?id='+id_first_week+'&player='+str(playerId)

    source = urllib.request.urlopen(url_player).read()
    soup = bs.BeautifulSoup(source,'lxml')

    tables = soup.find_all('table', attrs={'class':'ruler'})

    player_tournaments_results = []

    for table in tables:
        caption = table.find('caption')
        if "Men's Singles results of "+player_name in caption.text:
            table_rows = table.find_all('tr')
            for tr in table_rows:
                cols = tr.find_all('td')
                if len(cols)>=6:
                    #0: Tournament, 1: Week, 2: Result, 3: Points, 4: Matches 5: Used for calculation
                    link_to_matchs = cols[4].find('a').get('href')
                    used_for_calculation = len(cols[5].find_all('img'))>=1

                    player_tournaments_results.append([cols[1].text.strip().split('-')[0],cols[1].text.strip().split('-')[1],cols[0].text.strip(),cols[2].text.strip(),cols[3].text.strip(),used_for_calculation,link_to_matchs])

    df_player_tournaments_results = pd.DataFrame(player_tournaments_results,columns=['Year','Week','Tournament','Result','Points','Calculation','Matches'])

    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('int')
    df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Week'], ascending=True)
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('str')
    df_player_tournaments_results.reset_index(drop=True,inplace=True)

    df_player_tournaments_results.to_excel('./MEN_SINGLES_RESULTS/2022_'+player_name.replace(" ", "_")+'_RESULTS.xlsx',index=False)

In [90]:
#Simple Femmes
df_french_players = pd.read_excel('./FRANCE_PLAYERS/WOMEN_SINGLES_FRANCE_PLAYERS.xlsx')

df_french_players = df_french_players[df_french_players['Points']>=1000]

df_french_players

,Rank,Previous Rank,Short Country,Player,MemberId,Points,Tournaments,Confederation,Country,PlayerId
0,40,44,FRA,QI Xuefei,77256,30690,14,Europe,France,143810
1,50,50,FRA,LÃ©Onice HUET,88582,26712,16,Europe,France,1725868
2,64,64,FRA,Yaelle HOYAUX,82409,19195,14,Europe,France,454429
3,153,172,FRA,Rosy Oktavia PANCASARI,65540,8780,11,Europe,France,353124
4,166,164,FRA,Malya HOAREAU,71108,8010,9,Europe,France,4253369
5,177,177,FRA,Marie BATOMENE,94743,6840,4,Europe,France,306541
6,179,197,FRA,Anna TATRANOVA,71285,6790,11,Europe,France,2018084
7,198,199,FRA,Romane CLOTEAUX-FOUCAULT,78135,6010,7,Europe,France,2026147
8,296,265,FRA,Emilie DROUIN,66863,3126,8,Europe,France,2017940
9,393,391,FRA,Floriane NURIT,78240,2030,6,Europe,France,2870847
10,474,461,FRA,Marie CESARI,66369,1360,4,Europe,France,3102731
11,507,501,FRA,Alicia HUYNH,58630,1050,3,Europe,France,3080379

In [91]:
#On va rÃ©cupÃ¨rer la liste des tournois des joueurs au 1er Janvier 2023
id_first_week = "32857"

for i in range(len(df_french_players)):
    playerId = df_french_players['PlayerId'].iloc[i]

    player_name = df_french_players['Player'].iloc[i]

    url_player = 'https://bwf.tournamentsoftware.com/ranking/player.aspx?id='+id_first_week+'&player='+str(playerId)

    source = urllib.request.urlopen(url_player).read()
    soup = bs.BeautifulSoup(source,'lxml')

    tables = soup.find_all('table', attrs={'class':'ruler'})

    player_tournaments_results = []

    for table in tables:
        caption = table.find('caption')
        if "Women's Singles results of "+player_name in caption.text:
            table_rows = table.find_all('tr')
            for tr in table_rows:
                cols = tr.find_all('td')
                if len(cols)>=6:
                    #0: Tournament, 1: Week, 2: Result, 3: Points, 4: Matches 5: Used for calculation
                    link_to_matchs = cols[4].find('a').get('href')
                    used_for_calculation = len(cols[5].find_all('img'))>=1

                    player_tournaments_results.append([cols[1].text.strip().split('-')[0],cols[1].text.strip().split('-')[1],cols[0].text.strip(),cols[2].text.strip(),cols[3].text.strip(),used_for_calculation,link_to_matchs])

    df_player_tournaments_results = pd.DataFrame(player_tournaments_results,columns=['Year','Week','Tournament','Result','Points','Calculation','Matches'])
    
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('int')
    df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Week'], ascending=True)
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('str')
    df_player_tournaments_results.reset_index(drop=True,inplace=True)

    df_player_tournaments_results.to_excel('./WOMEN_SINGLES_RESULTS/2022_'+player_name.replace(" ", "_")+'_RESULTS.xlsx',index=False)

In [92]:
#Double hommes
df_french_players = pd.read_excel('./FRANCE_PLAYERS/MEN_DOUBLES_FRANCE_PLAYERS.xlsx')

df_french_players = df_french_players[df_french_players['Points']>=1000]

df_french_players['Previous Rank'] = df_french_players['Previous Rank'].astype('int')

df_french_players

,Rank,Previous Rank,Short Country,Player1,Player2,MemberId1,MemberId2,Points,Tournaments,Confederation,Country,PlayerId1,PlayerId2
0,33,33,FRA,Christo POPOV,Toma Junior POPOV,72885,61628,34788,18,Europe,France,1995693,674117
1,36,36,FRA,Lucas CORVEE,Ronan LABAR,89416,22038,32069,18,Europe,France,197408,108392
2,48,44,FRA,Fabien DELRUE,William VILLEGER,91739,88264,25545,8,Europe,France,1725909,1995906
3,79,87,FRA,Julien MAIO,William VILLEGER,73323,88264,15420,7,Europe,France,300576,1995906
4,90,89,FRA,Kenji LOVANG,Leo ROSSI,62969,96690,12810,13,Europe,France,2026221,393198
5,122,118,FRA,Eloi ADAM,Julien MAIO,87403,73323,8880,5,Europe,France,1426878,300576
6,130,134,FRA,Mael CATTOEN,Lucas RENOIR,91112,78192,8260,9,Europe,France,3489609,2017976
7,178,190,FRA,Nicolas HOAREAU,Aymeric TORES,95473,88871,5410,10,Europe,France,2018193,2875464
8,191,187,FRA,Louis DUCROT,Romain FRANK,99461,76496,4920,5,Europe,France,1199368,2442048
9,208,207,FRA,Samy CORVEE,Yanis GAUDIN,56409,83581,4410,6,Europe,France,1426960,2018454
10,276,343,FRA,Quentin RONGET,Edgar ROUX,96472,96530,3350,6,Europe,France,2875604,2875266
11,350,347,FRA,Natan BEGGA,Baptiste LABARTHE,59578,98466,2350,3,Europe,France,3611103,3489364
12,370,367,FRA,Nicolas HOAREAU,Arthur WAKHEVITSCH,95473,66224,2200,1,Europe,France,2018193,2018553
13,408,404,FRA,Eloi ADAM,Samy CORVEE,87403,56409,1840,2,Europe,France,1426878,1426960
14,431,426,FRA,Thom GICQUEL,Toma Junior POPOV,68544,61628,1775,1,Europe,France,1354995,674117
15,484,476,FRA,Samy CORVEE,Louis DUCROT,56409,99461,1520,1,Europe,France,1426960,1199368
16,578,566,FRA,Tom LALOT TRESCARTE,Kimi LOVANG,59160,69841,1280,5,Europe,France,4320278,2870892
17,592,581,FRA,Simon BARON-VEZILIER,Quentin RONGET,66522,96472,1170,1,Europe,France,2018012,2875604
18,608,794,FRA,Natan BEGGA,Kimi LOVANG,59578,69841,1100,2,Europe,France,3611103,2870892

In [93]:
#On va rÃ©cupÃ¨rer la liste des tournois des joueurs au 1er Janvier 2023
id_first_week = "32857"

for i in range(len(df_french_players)):
    playerId = df_french_players['PlayerId1'].iloc[i]

    player_name = df_french_players['Player1'].iloc[i]
    player_partner_name = df_french_players['Player2'].iloc[i]

    url_player = 'https://bwf.tournamentsoftware.com/ranking/player.aspx?id='+id_first_week+'&player='+str(playerId)

    source = urllib.request.urlopen(url_player).read()
    soup = bs.BeautifulSoup(source,'lxml')

    tables = soup.find_all('table', attrs={'class':'ruler'})

    player_tournaments_results = []

    for table in tables:
        caption = table.find('caption')
        if "Men's Doubles results of "+player_name+' / '+player_partner_name in caption.text:
            table_rows = table.find_all('tr')
            for tr in table_rows:
                cols = tr.find_all('td')
                if len(cols)>=6:
                    #0: Tournament, 1: Week, 2: Result, 3: Points, 4: Matches 5: Used for calculation
                    link_to_matchs = cols[4].find('a').get('href')
                    used_for_calculation = len(cols[5].find_all('img'))>=1

                    player_tournaments_results.append([cols[1].text.strip().split('-')[0],cols[1].text.strip().split('-')[1],cols[0].text.strip(),cols[2].text.strip(),cols[3].text.strip(),used_for_calculation,link_to_matchs])

    df_player_tournaments_results = pd.DataFrame(player_tournaments_results,columns=['Year','Week','Tournament','Result','Points','Calculation','Matches'])
    
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('int')
    df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Week'], ascending=True)
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('str')
    df_player_tournaments_results.reset_index(drop=True,inplace=True)

    df_player_tournaments_results.to_excel('./MEN_DOUBLES_RESULTS/2022_'+player_name.replace(" ", "_")+'_AND_'+player_partner_name.replace(" ", "_")+'_RESULTS.xlsx',index=False)

In [94]:
#Double Femmes
df_french_players = pd.read_excel('./FRANCE_PLAYERS/WOMEN_DOUBLES_FRANCE_PLAYERS.xlsx')

df_french_players = df_french_players[df_french_players['Points']>=1000]

df_french_players

,Rank,Previous Rank,Short Country,Player1,Player2,MemberId1,MemberId2,Points,Tournaments,Confederation,Country,PlayerId1,PlayerId2
0,31,30.0,FRA,Margot LAMBERT,Anne TRAN,99891,98854,36014,18,Europe,France,1355183,356059
1,65,63.0,FRA,Flavie VALLET,Emilie VERCELOT,63229,72254,18335,12,Europe,France,2406661,2018301
2,234,235.0,FRA,Romane CLOTEAUX-FOUCAULT,Anouk NAMBOT,78135,89788,3360,4,Europe,France,2026147,3491931
3,251,255.0,FRA,Tea MARGUERITTE,Camille POGNANTE,73899,84050,3040,3,Europe,France,2870940,3489805
4,264,201.0,FRA,Tea MARGUERITTE,Anna TATRANOVA,73899,71285,2960,2,Europe,France,2870940,2018084
5,292,295.0,FRA,Vimala HERIAU,Margot LAMBERT,90317,99891,2604,1,Europe,France,1225702,1355183
6,294,297.0,FRA,Caroline CHENG,Camille YVENAT,75962,71304,2560,3,Europe,France,3152573,5417016
7,312,314.0,FRA,Kathell DESMOTS-CHACUN,Clemence GAUDREAU,94687,58225,2220,4,Europe,France,3489854,4029565
8,339,340.0,FRA,Herveline CRESPEL,Elsa JACOB,92471,77589,2080,4,Europe,France,3489707,4280460
9,351,352.0,FRA,Marie CESARI,Lilou SCHAFFNER,66369,55869,1870,3,Europe,France,3102731,4340022
10,366,345.0,FRA,Alicia HUYNH,Floriane NURIT,58630,78240,1820,3,Europe,France,3080379,2870847
11,375,374.0,FRA,Clemence GAUDREAU,Elsa JACOB,58225,77589,1720,2,Europe,France,4029565,4280460
12,384,224.0,FRA,Malya HOAREAU,Camille POGNANTE,71108,84050,1670,1,Europe,France,4253369,3489805
13,463,454.0,FRA,Delphine DELRUE,Margot LAMBERT,70762,99891,1393,1,Europe,France,674128,1355183
14,464,NaN,FRA,Sharone BAUER,Emilie VERCELOT,98332,72254,1370,1,Europe,France,2291359,2018301
15,464,NaN,FRA,Tea MARGUERITTE,Flavie VALLET,73899,63229,1370,1,Europe,France,2870940,2406661
16,489,479.0,FRA,Carla DUBOIS,Elena PHAN,72095,76802,1270,2,Europe,France,4280402,3916504

In [95]:
#On va rÃ©cupÃ¨rer la liste des tournois des joueurs au 1er Janvier 2023
id_first_week = "32857"

for i in range(len(df_french_players)):
    playerId = df_french_players['PlayerId1'].iloc[i]

    player_name = df_french_players['Player1'].iloc[i]
    player_partner_name = df_french_players['Player2'].iloc[i]

    url_player = 'https://bwf.tournamentsoftware.com/ranking/player.aspx?id='+id_first_week+'&player='+str(playerId)

    source = urllib.request.urlopen(url_player).read()
    soup = bs.BeautifulSoup(source,'lxml')

    tables = soup.find_all('table', attrs={'class':'ruler'})

    player_tournaments_results = []

    for table in tables:
        caption = table.find('caption')
        if "Women's Doubles results of "+player_name+' / '+player_partner_name in caption.text:
            table_rows = table.find_all('tr')
            for tr in table_rows:
                cols = tr.find_all('td')
                if len(cols)>=6:
                    #0: Tournament, 1: Week, 2: Result, 3: Points, 4: Matches 5: Used for calculation
                    link_to_matchs = cols[4].find('a').get('href')
                    used_for_calculation = len(cols[5].find_all('img'))>=1

                    player_tournaments_results.append([cols[1].text.strip().split('-')[0],cols[1].text.strip().split('-')[1],cols[0].text.strip(),cols[2].text.strip(),cols[3].text.strip(),used_for_calculation,link_to_matchs])

    df_player_tournaments_results = pd.DataFrame(player_tournaments_results,columns=['Year','Week','Tournament','Result','Points','Calculation','Matches'])

    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('int')
    df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Week'], ascending=True)
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('str')
    df_player_tournaments_results.reset_index(drop=True,inplace=True)

    df_player_tournaments_results.to_excel('./WOMEN_DOUBLES_RESULTS/2022_'+player_name.replace(" ", "_")+'_AND_'+player_partner_name.replace(" ", "_")+'_RESULTS.xlsx',index=False)

In [6]:
#Double Mixte
df_french_players = pd.read_excel('./FRANCE_PLAYERS/MIXED_DOUBLES_FRANCE_PLAYERS.xlsx')

df_french_players = df_french_players[df_french_players['Points']>=1000]

df_french_players

array(['Thom GICQUEL / Delphine DELRUE', 'William VILLEGER / Anne TRAN',
       'Lucas CORVEE / Sharone BAUER', 'Fabien DELRUE / Vimala HERIAU',
       'Enogat ROY / Anna TATRANOVA', 'Samy CORVEE / Flavie VALLET',
       'Tino DAOUDAL / Malya HOAREAU', 'Mael CATTOEN / Camille POGNANTE',
       'Lucas RENOIR / Tea MARGUERITTE',
       'GrÃ©goire DESCHAMP / Emilie VERCELOT',
       'Corentin LECERF / Lorraine BAUMANN',
       'Yohan BARBIERI / Elsa JACOB', 'Tom LALOT TRESCARTE / Elsa JACOB',
       'Julien MAIO / Lea PALERMO', 'Lucas CLAERBOUT / Yaelle HOYAUX',
       'Aymeric TORES / Anouk NAMBOT', 'Julien MAIO / Vimala HERIAU',
       'Eloi ADAM / Sharone BAUER', 'William VILLEGER / Flavie VALLET',
       'Jordan CORVEE / HÃ©loÃ¯se LE MOULEC',
       'Natan BEGGA / Herveline CRESPEL',
       'Baptiste LABARTHE / Kathell DESMOTS-CHACUN'], dtype=object)

In [97]:
#On va rÃ©cupÃ¨rer la liste des tournois des joueurs au 1er Janvier 2023
id_first_week = "32857"

for i in range(len(df_french_players)):
    playerId = df_french_players['PlayerId1'].iloc[i]

    player_name = df_french_players['Player1'].iloc[i]
    player_partner_name = df_french_players['Player2'].iloc[i]

    url_player = 'https://bwf.tournamentsoftware.com/ranking/player.aspx?id='+id_first_week+'&player='+str(playerId)

    source = urllib.request.urlopen(url_player).read()
    soup = bs.BeautifulSoup(source,'lxml')

    tables = soup.find_all('table', attrs={'class':'ruler'})

    player_tournaments_results = []

    for table in tables:
        caption = table.find('caption')
        if "Mixed Doubles results of "+player_name+' / '+player_partner_name in caption.text:
            table_rows = table.find_all('tr')
            for tr in table_rows:
                cols = tr.find_all('td')
                if len(cols)>=6:
                    #0: Tournament, 1: Week, 2: Result, 3: Points, 4: Matches 5: Used for calculation
                    link_to_matchs = cols[4].find('a').get('href')
                    used_for_calculation = len(cols[5].find_all('img'))>=1

                    player_tournaments_results.append([cols[1].text.strip().split('-')[0],cols[1].text.strip().split('-')[1],cols[0].text.strip(),cols[2].text.strip(),cols[3].text.strip(),used_for_calculation,link_to_matchs])

    df_player_tournaments_results = pd.DataFrame(player_tournaments_results,columns=['Year','Week','Tournament','Result','Points','Calculation','Matches'])

    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('int')
    df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Week'], ascending=True)
    df_player_tournaments_results['Week'] = df_player_tournaments_results['Week'].astype('str')
    df_player_tournaments_results.reset_index(drop=True,inplace=True)

    df_player_tournaments_results.to_excel('./MIXED_DOUBLES_RESULTS/2022_'+player_name.replace(" ", "_")+'_AND_'+player_partner_name.replace(" ", "_")+'_RESULTS.xlsx',index=False)

# Calcul des points

In [3]:
df_player_tournaments_results = pd.read_excel('./MEN_SINGLES_RESULTS/2022_Toma_Junior_POPOV_RESULTS.xlsx')
df_player_tournaments_results

,Year,Week,Tournament,Result,Points,Calculation,Matches
0,2022,4,DAIHATSU Indonesia Masters 2022,17/32,2220,False,../sport/player.aspx?id=F75FB4EC-43FB-4E92-98F...
1,2022,10,YONEX GAINWARD German Open 2022,9/16,2750,True,../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
2,2022,11,YONEX All England Open Badminton Championships...,17/32,3000,True,../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
3,2022,12,YONEX Swiss Open 2022,5/8,3850,True,../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
4,2022,13,Orleans Masters 2022,1,5500,True,../sport/player.aspx?id=A8B53352-A398-4564-BF2...
5,2022,17,2022 European Championships,3/4,6420,True,../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
6,2022,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,1,5243,True,../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
7,2022,20,GR TOYOTA GAZOO RACING Thailand Open 2022,9/16,3600,True,../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
8,2022,24,EAST VENTURES Indonesia Open 2022,9/16,4800,True,../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
9,2022,34,TotalEnergies BWF World Championships 2022,33/64,1300,False,../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...
10,2022,35,DAIHATSU YONEX Japan Open 2022,17/32,2660,True,../sport/player.aspx?id=29025589-10CA-4357-906...
11,2022,42,Denmark Open 2022 presented by VICTOR,17/32,2660,False,../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12,2022,43,YONEX French Open 2022,17/32,2660,False,../sport/player.aspx?id=10B084D8-292F-4586-874...
13,2022,44,HYLO Open 2022,3/4,4900,True,../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...

In [4]:
df_2022_tournaments_list = pd.read_excel("./BWF_TOURNAMENTS/2022_BWF_TOURNAMENTS_LIST_WITH_DISTRIBUTION_AND_KEY_DATES.xlsx")
df_2022_tournaments_list

,Month,Week,Dates,Continent,Country,City,Tournament,Category,Team,1,...,513-1024,Entry Deadline,World Ranking Date,M & Q Report,Seeding Date,Withdrawal Deadline,Draw Date,Tournament Link,Website,Updated Date
0,1,2,11 -16,Asia,IND,New Delhi,YONEX-SUNRISE India Open 2022,HSBC BWF World Tour Super 500,0,9200.0,...,40.0,07/12/2021,07/12/2021,10/12/2021,14/12/2021,20/12/2021,21/12/2021,https://bwf.tournamentsoftware.com/sport/tourn...,NaN,21/03/2023
1,1,2,13 -16,Europe,EST,Tallinn,YONEX Estonian International 2022,International Series,0,2500.0,...,10.0,14/12/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
2,1,3,18 -23,Asia,IND,Lucknow,Syed Modi India International 2022,HSBC BWF World Tour Super 300,0,7000.0,...,30.0,21/12/2021,21/12/2021,24/12/2021,21/12/2021,27/12/2021,28/12/2021,https://bwf.tournamentsoftware.com/sport/tourn...,NaN,21/03/2023
3,1,3,20 -23,Europe,SWE,uppsala,VICTOR Swedish Open 2022,International Series,0,2500.0,...,10.0,21/12/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
4,1,4,25 -30,Asia,IND,Cuttack,Odisha Open 2022,BWF Tour Super 100,0,5500.0,...,30.0,28/12/2021,28/12/2021,31/12/2021,28/12/2021,03/01/2022,04/01/2022,https://bwf.tournamentsoftware.com/sport/tourn...,NaN,21/03/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,12,49,07 -11,Asia,THA,Bangkok,HSBC BWF World Tour Finals 2022,HSBC BWF World Tour Finals,0,12000.0,...,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,12,49,08 -11,Europe,MLT,Cospicua,Malta International 2022 presented by VICTOR,Future Series,0,1700.0,...,5.0,08/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
135,12,50,13 -18,Asia,MAS,Ipoh,PETRONAS Malaysia International Challenge 2022...,International Challenge,0,4000.0,...,20.0,22/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
136,12,50,15 -18,Europe,BUL,Sofia,2023 European Mixed Team Championships - Quali...,Continental Team Championships,1,NaN,...,NaN,12/12/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023
137,12,51,19 -22,Asia,TUR,Ankara,Turkey Open 2022 (Cancelled),International Series,0,2500.0,...,10.0,22/11/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21/03/2023

In [5]:
#Fonction qui va catÃ©goriser les tournois
def get_category_tournaments(df_player_tournaments_results,df_tournaments_list):
    #On regarde si les tournois sont par equipe
    for i in range(len(df_player_tournaments_results)):
        df_tournament_details = df_tournaments_list[df_tournaments_list['Tournament']==df_player_tournaments_results['Tournament'].iloc[i]]
        df_player_tournaments_results.loc[i,'Team'] = df_tournament_details['Team'].values[0]
    
        if df_tournament_details['Category'].iloc[0]=='Continental Individual Games' or df_tournament_details['Category'].iloc[0]=='Multi-Sport Games':
            df_player_tournaments_results.loc[i,'Continental Games'] = 1
        else:
            df_player_tournaments_results.loc[i,'Continental Games'] = 0

        if df_tournament_details['Category'].iloc[0]=='Continental Individual Championships':
            df_player_tournaments_results.loc[i,'Continental Championships'] = 1
        else:
            df_player_tournaments_results.loc[i,'Continental Championships'] = 0

        if "World Championships" in df_tournament_details['Tournament'].iloc[0]:
            df_player_tournaments_results.loc[i,'World Championships'] = 1
        else:
            df_player_tournaments_results.loc[i,'World Championships'] = 0

    df_player_tournaments_results['Team'] = df_player_tournaments_results['Team'].astype('int')
    df_player_tournaments_results['Continental Games'] = df_player_tournaments_results['Continental Games'].astype('int')
    df_player_tournaments_results['Continental Championships'] = df_player_tournaments_results['Continental Championships'].astype('int')
    df_player_tournaments_results['World Championships'] = df_player_tournaments_results['World Championships'].astype('int')

    return df_player_tournaments_results

#Fonction qui renvoie la liste des tournois avec un attribut "Calculation"=True pour les tournois qui comptent pour le classement
def get_world_ranking(df_player_tournaments_results):
    #On les classe par ordre de points
    df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Points'], ascending=False)
    #On reset les indices
    df_player_tournaments_results.reset_index(drop=True,inplace=True)
    #Initialisation 
    df_player_tournaments_results['Calculation']=False
    df_tournaments_for_calculation = df_player_tournaments_results.iloc[0:1]
    #On parcourt tous les tournois et on vÃ©rifie qu'ils respectent les conditions pour le classement mondial
    for i in range(1,len(df_player_tournaments_results)):
        if len(df_tournaments_for_calculation)<10:
            df_tournaments_for_calculation = pd.concat([df_tournaments_for_calculation,df_player_tournaments_results.iloc[i:i+1]])
            #On regarde si il y a deux tournois par equipe
            if df_tournaments_for_calculation['Team'].sum()>1:
                index_team = df_tournaments_for_calculation.index[df_tournaments_for_calculation['Team']==1].tolist()
                if df_tournaments_for_calculation.loc[index_team[0],"Points"]>=df_tournaments_for_calculation.loc[index_team[1],"Points"]:
                    print(df_tournaments_for_calculation.loc[index_team[0],"Points"])
                    df_tournaments_for_calculation.drop(index_team[1], inplace=True)
                else:
                    df_tournaments_for_calculation.drop(index_team[0], inplace=True)

            #On regarde si il y a deux jeux continentaux
            if df_tournaments_for_calculation['Continental Games'].sum()>1:
                index_cont_games = df_tournaments_for_calculation.index[df_tournaments_for_calculation['Continental Games']==1].tolist()
                if df_tournaments_for_calculation.loc[index_cont_games[0],"Points"]>=df_tournaments_for_calculation.loc[index_cont_games[1],"Points"]:
                    df_tournaments_for_calculation.drop(index_cont_games[1], inplace=True)
                else:
                    df_tournaments_for_calculation.drop(index_cont_games[0], inplace=True)

            #On regarde si il y a deux championnats continentaux
            if df_tournaments_for_calculation['Continental Championships'].sum()>1:
                index_cont_champ = df_tournaments_for_calculation.index[df_tournaments_for_calculation['Continental Championships']==1].tolist()
                if df_tournaments_for_calculation.loc[index_cont_champ[0],"Points"]>=df_tournaments_for_calculation.loc[index_cont_champ[1],"Points"]:
                    df_tournaments_for_calculation.drop(index_cont_champ[1], inplace=True)
                else:
                    df_tournaments_for_calculation.drop(index_cont_champ[0], inplace=True)

            #On regarde si il y a deux championnats du monde       
            if df_tournaments_for_calculation['World Championships'].sum()>1:
                index_world_champ = df_tournaments_for_calculation.index[df_tournaments_for_calculation['World Championships']==1].tolist()
                if df_tournaments_for_calculation.loc[index_world_champ[0],"Points"]>=df_tournaments_for_calculation.loc[index_world_champ[1],"Points"]:
                    df_tournaments_for_calculation.drop(index_world_champ[1], inplace=True)
                else:
                    df_tournaments_for_calculation.drop(index_world_champ[0], inplace=True)

    #On rÃ©cupÃ¨re les indices des tournois pour le calcul du classement
    index_tournaments_for_calculation = df_tournaments_for_calculation.index
    for idx in index_tournaments_for_calculation:
        df_player_tournaments_results.loc[idx,"Calculation"] = True
        
    return df_player_tournaments_results

In [6]:
df_player_tournaments_results = get_category_tournaments(df_player_tournaments_results,df_2022_tournaments_list)
df_player_tournaments_results = get_world_ranking(df_player_tournaments_results)
df_player_tournaments_results

,Year,Week,Tournament,Result,Points,Calculation,Matches,Team,Continental Games,Continental Championships,World Championships
0,2022,17,2022 European Championships,3/4,6420,True,../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...,0,0,1,0
1,2022,13,Orleans Masters 2022,1,5500,True,../sport/player.aspx?id=A8B53352-A398-4564-BF2...,0,0,0,0
2,2022,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,1,5243,True,../sport/player.aspx?id=4E68E080-BF68-463C-ACA...,1,0,0,0
3,2022,44,HYLO Open 2022,3/4,4900,True,../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...,0,0,0,0
4,2022,24,EAST VENTURES Indonesia Open 2022,9/16,4800,True,../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...,0,0,0,0
5,2022,12,YONEX Swiss Open 2022,5/8,3850,True,../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...,0,0,0,0
6,2022,20,GR TOYOTA GAZOO RACING Thailand Open 2022,9/16,3600,True,../sport/player.aspx?id=E16742AE-6672-4B41-8B2...,0,0,0,0
7,2022,11,YONEX All England Open Badminton Championships...,17/32,3000,True,../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...,0,0,0,0
8,2022,10,YONEX GAINWARD German Open 2022,9/16,2750,True,../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...,0,0,0,0
9,2022,35,DAIHATSU YONEX Japan Open 2022,17/32,2660,True,../sport/player.aspx?id=29025589-10CA-4357-906...,0,0,0,0
10,2022,42,Denmark Open 2022 presented by VICTOR,17/32,2660,False,../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...,0,0,0,0
11,2022,43,YONEX French Open 2022,17/32,2660,False,../sport/player.aspx?id=10B084D8-292F-4586-874...,0,0,0,0
12,2022,4,DAIHATSU Indonesia Masters 2022,17/32,2220,False,../sport/player.aspx?id=F75FB4EC-43FB-4E92-98F...,0,0,0,0
13,2022,34,TotalEnergies BWF World Championships 2022,33/64,1300,False,../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...,0,0,0,1

# Simulation

In [7]:
df_player_tournaments_results = df_player_tournaments_results.sort_values(by=['Week'], ascending=True)
df_player_tournaments_results

,Year,Week,Tournament,Result,Points,Calculation,Matches,Team,Continental Games,Continental Championships,World Championships
12,2022,4,DAIHATSU Indonesia Masters 2022,17/32,2220,False,../sport/player.aspx?id=F75FB4EC-43FB-4E92-98F...,0,0,0,0
8,2022,10,YONEX GAINWARD German Open 2022,9/16,2750,True,../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...,0,0,0,0
7,2022,11,YONEX All England Open Badminton Championships...,17/32,3000,True,../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...,0,0,0,0
5,2022,12,YONEX Swiss Open 2022,5/8,3850,True,../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...,0,0,0,0
1,2022,13,Orleans Masters 2022,1,5500,True,../sport/player.aspx?id=A8B53352-A398-4564-BF2...,0,0,0,0
0,2022,17,2022 European Championships,3/4,6420,True,../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...,0,0,1,0
2,2022,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,1,5243,True,../sport/player.aspx?id=4E68E080-BF68-463C-ACA...,1,0,0,0
6,2022,20,GR TOYOTA GAZOO RACING Thailand Open 2022,9/16,3600,True,../sport/player.aspx?id=E16742AE-6672-4B41-8B2...,0,0,0,0
4,2022,24,EAST VENTURES Indonesia Open 2022,9/16,4800,True,../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...,0,0,0,0
13,2022,34,TotalEnergies BWF World Championships 2022,33/64,1300,False,../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...,0,0,0,1
9,2022,35,DAIHATSU YONEX Japan Open 2022,17/32,2660,True,../sport/player.aspx?id=29025589-10CA-4357-906...,0,0,0,0
10,2022,42,Denmark Open 2022 presented by VICTOR,17/32,2660,False,../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...,0,0,0,0
11,2022,43,YONEX French Open 2022,17/32,2660,False,../sport/player.aspx?id=10B084D8-292F-4586-874...,0,0,0,0
3,2022,44,HYLO Open 2022,3/4,4900,True,../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...,0,0,0,0

In [8]:
#On va trouver la semaine la plus Ã©levÃ©e parmis les simulations (resp. la plus petite)
max_week =  df_player_tournaments_results['Week'].max()
min_week =  df_player_tournaments_results.loc[df_player_tournaments_results['Calculation']==True,'Week'].min()

total_points = df_player_tournaments_results.loc[df_player_tournaments_results['Calculation']==True,'Points'].sum()

#On va calculer le nombre de points au fur et Ã  mesure des semaines 
points = [0]*52

df_week_ranking = pd.DataFrame(columns = ['Simulation','Week','Tournament','Result','Points Earned','Points to defend','Total Ranking Points'])

for week in range(1,min_week+1):
    points[week-1] = total_points
    df_week_ranking.loc[len(df_week_ranking)]=[False,week,"No Tournament","",0,0,points[week-1]]
        
for week in range(min_week+1,max_week+2):
    df_player_tournaments_results_simulated = df_player_tournaments_results[df_player_tournaments_results['Week']>=week]
    df_player_tournaments_results_simulated = get_world_ranking(df_player_tournaments_results_simulated)
    total_points = df_player_tournaments_results_simulated.loc[df_player_tournaments_results_simulated['Calculation']==True,'Points'].sum()
    points[week-1] = total_points
    df_week_ranking.loc[len(df_week_ranking)]=[True,week,"No Tournament","",0,0,points[week-1]]
    
    df_week = df_player_tournaments_results[df_player_tournaments_results["Week"]==week-1]
    if len(df_week)>0:
        df_week_ranking.loc[week-2,'Tournament']=df_week['Tournament'].values[0]
        df_week_ranking.loc[week-2,'Points Earned']=df_week['Points'].values[0]
        
for week in range(max_week+2,53):
    points[week-1] = 0
    df_week_ranking.loc[len(df_week_ranking)]=[False,week,"No Tournament","",0,0,points[week-1]]

    
    
    
#     df_week = df_player_tournaments_results[df_player_tournaments_results["Week"]==week]
#     #Si on a un tournoi sur cette semaine:
#     if len(df_week)>0:
#         #Calcule des points
#         if df_week['Calculation'].iloc[0]==True and week!=1:
#             points[week]=points[week-1]-df_week['Points'].iloc[0]
#         elif df_week['Calculation'].iloc[0]==True and week==1:
#             points[week]=points[week]-df_week['Points'].iloc[0]
#         elif week>=2:
#             points[week]=points[week-1]

#         if df_week['Calculation'].iloc[0]==True:
#             df_week_ranking.loc[len(df_week_ranking)]=[False,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],df_week['Points'].iloc[0],points[week-1]]
#         else:
#             df_week_ranking.loc[len(df_week_ranking)]=[False,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],0,points[week-1]]

#     elif week>=1:
#         points[week]=points[week-1]
#         df_week_ranking.loc[len(df_week_ranking)]=[False,week,"No Tournament","",0,0,points[week-1]]

        
# if max_week<52:
#     for week in range(max_week+2,53):
#         points[week-1]=points[week-2]-df_week_ranking['Points to defend'].iloc[week-1]
#         df_week = df_player_tournaments_results_simulated[df_player_tournaments_results_simulated["Week"]==week-1]
#         print(df_week)
#         #Si on a un tournoi sur cette semaine:
#         if len(df_week)>0:
#             #Calcule des points
#             if df_week['Calculation'].iloc[0]==True and week!=1:
#                 points[week-1]=points[week-2]-df_week['Points'].iloc[0]
#             elif df_week['Calculation'].iloc[0]==True and week==1:
#                 points[week-1]=points[week-1]-df_week['Points'].iloc[0]
#             elif week>=2:
#                 points[week-1]=points[week-2]

#             if df_week['Calculation'].iloc[0]==True:
#                 df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],df_week['Points'].iloc[0],points[week-1]]
                
#         elif week>=1:
#             points[week-1]=points[week-2]
#             df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,"No Tournament","",0,0,points[week-1]]
                
        

df_week_ranking

,Simulation,Week,Tournament,Result,Points Earned,Points to defend,Total Ranking Points
0,False,1,No Tournament,,0,0,42723
1,False,2,No Tournament,,0,0,42723
2,False,3,No Tournament,,0,0,42723
3,False,4,No Tournament,,0,0,42723
4,False,5,No Tournament,,0,0,42723
5,False,6,No Tournament,,0,0,42723
6,False,7,No Tournament,,0,0,42723
7,False,8,No Tournament,,0,0,42723
8,False,9,No Tournament,,0,0,42723
9,False,10,YONEX GAINWARD German Open 2022,,2750,0,42723
10,True,11,YONEX All England Open Badminton Championships...,,3000,0,42633
11,True,12,YONEX Swiss Open 2022,,3850,0,42293
12,True,13,Orleans Masters 2022,,5500,0,39743
13,True,14,No Tournament,,0,0,34243
14,True,15,No Tournament,,0,0,34243
15,True,16,No Tournament,,0,0,34243
16,True,17,2022 European Championships,,6420,0,34243
17,True,18,No Tournament,,0,0,27823
18,True,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,,5243,0,27823
19,True,20,GR TOYOTA GAZOO RACING Thailand Open 2022,,3600,0,22580
20,True,21,No Tournament,,0,0,18980
21,True,22,No Tournament,,0,0,18980
22,True,23,No Tournament,,0,0,18980
23,True,24,EAST VENTURES Indonesia Open 2022,,4800,0,18980
24,True,25,No Tournament,,0,0,14180
25,True,26,No Tournament,,0,0,14180
26,True,27,No Tournament,,0,0,14180
27,True,28,No Tournament,,0,0,14180
28,True,29,No Tournament,,0,0,14180
29,True,30,No Tournament,,0,0,14180
30,True,31,No Tournament,,0,0,14180
31,True,32,No Tournament,,0,0,14180
32,True,33,No Tournament,,0,0,14180
33,True,34,TotalEnergies BWF World Championships 2022,,1300,0,14180
34,True,35,DAIHATSU YONEX Japan Open 2022,,2660,0,12880
35,True,36,No Tournament,,0,0,10220
36,True,37,No Tournament,,0,0,10220
37,True,38,No Tournament,,0,0,10220
38,True,39,No Tournament,,0,0,10220
39,True,40,No Tournament,,0,0,10220
40,True,41,No Tournament,,0,0,10220
41,True,42,Denmark Open 2022 presented by VICTOR,,2660,0,10220
42,True,43,YONEX French Open 2022,,2660,0,7560
43,True,44,HYLO Open 2022,,4900,0,4900
44,True,45,No Tournament,,0,0,0
45,False,46,No Tournament,,0,0,0
46,False,47,No Tournament,,0,0,0
47,False,48,No Tournament,,0,0,0
48,False,49,No Tournament,,0,0,0
49,False,50,No Tournament,,0,0,0
50,False,51,No Tournament,,0,0,0
51,False,52,No Tournament,,0,0,0

In [13]:
import plotly.graph_objects as go


custom_data = np.stack((df_week_ranking['Tournament'],df_week_ranking['Result'],df_week_ranking['Points Earned'],df_week_ranking['Points to defend']), axis=-1)

fig = go.Figure(data=go.Scatter(x=df_week_ranking['Week'],
                            y=df_week_ranking['Total Ranking Points'],
                            customdata=custom_data,
                            name="Ranking",
                            marker_color=df_week_ranking['Points Earned'],
                            marker_colorscale="Plasma",
                            marker_showscale=False,
                            marker_size = 5,
                            fill="tozerox",
                            fillcolor="rgba(171,219,227,0.2)"))

fig.update_layout(title='Ranking Points Over Weeks',
                  xaxis_title="Week Number",
                  yaxis_title="Ranking Points",
                  hovermode=None
                  )

fig.update_traces(mode="markers+lines",
                  hovertemplate = '<b>Week %{x}:</b>'+
                  '<br><b>Total Ranking Points</b>: %{y}'+
                  '<br>Tournament: %{customdata[0]}'+
                  '<br>Result: %{customdata[1]}'+
                  '<br>Points Earned: %{customdata[2]}'+
                  '<br>Points to Defend: %{customdata[3]}')
fig.show()

In [29]:
#On crÃ©e le dataframe des tournois simulÃ©s
df_tournament_simulated = pd.DataFrame(columns=["Year","Week","Tournament","Result","Points","Calculation","Matches"])

In [30]:
#ATTENTION AU CAS OU ON A DEJA UN TOURNOIS CETTE SEMAINE LA, LE REMPLACER
tournament_name = "PETRONAS Malaysia Open 2023"
tournament_week = "2"
estimated_results = "17-32"

details_tournament = df_2023_tournaments_list[df_2023_tournaments_list['Tournament']==tournament_name]

points_earned = details_tournament[estimated_results].values[0]

In [188]:
#On vÃ©rifie si le tournoi a Ã©tÃ© jouÃ© en 2022.
import Levenshtein

def clean_tournament_name(tournament_name):
    name_split = tournament_name.split(' ')
    name = ""
    for word in name_split:
        word = word.strip()
        if not word.isupper() and word!="-" and word!="2023" and word!="2022" and word!="(New dates)" and word!="(Cancelled)" and word!="(Postponed)" and word!="presented" and word!="by" and word!="Cancelled" and word!="Non Tournament" and word!="(New Dates)":
            name += word+" "
    
    return name.strip()

tournament_name_clean = clean_tournament_name(tournament_name)

print(tournament_name_clean)

for i in range(len(df_player_tournaments_results)):
    print(Levenshtein.distance(tournament_name_clean,clean_tournament_name(df_player_tournaments_results['Tournament'].iloc[i])))
    

    
#On vÃ©rifie que l'on a pas ajoutÃ©

Malaysia Open
12
8
33
7
11
19
33
7
6
27
6
8
8
9

In [32]:
#On ajoute le tournoi simulÃ©

df_tournament_simulated.loc[len(df_tournament_simulated)]= [2023,int(2),'PETRONAS Malaysia Open 2023','17-32',3000,False,""]
df_tournament_simulated

   Year  Week                   Tournament Result  Points  Calculation Matches
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000        False

In [34]:
#On regarde la catÃ©gorie du tournois
df_tournament_simulated = df_tournament_simulated.sort_values(by=['Week'], ascending=True)
df_tournament_simulated.reset_index(drop=True,inplace=True)
df_tournament_simulated = get_category_tournaments(df_tournament_simulated,df_2023_tournaments_list)

df_tournament_simulated

,Year,Week,Tournament,Result,Points,Calculation,Matches,Team,Continental Games,Continental Championships,World Championships
0,2023,2,PETRONAS Malaysia Open 2023,17-32,3000,False,,0,0,0,0

In [38]:
#On va trouver la semaine la plus Ã©levÃ©e parmis les simulations (resp. la plus petite)
max_week = df_tournament_simulated['Week'].max()
min_week = df_tournament_simulated['Week'].min()

#On va calculer le nombre de points au fur et Ã  mesure des semaines 
points = [0]*52

df_week_ranking_simulated = pd.DataFrame(columns = ['Simulation','Week','Tournament','Result','Points Earned','Points to defend','Total Ranking Points'])


for week in range(1,min_week+1):
    points[week-1] = df_week_ranking['Total Ranking Points'].iloc[week-1]
    df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,"No Tournament","",0,0,points[week-1]]

for week in range(min_week+1,53):
    df_player_tournaments_results_simulated = pd.concat([df_player_tournaments_results[df_player_tournaments_results['Week']>=week],df_tournament_simulated[df_tournament_simulated['Week']<week]])
    df_player_tournaments_results_simulated = get_world_ranking(df_player_tournaments_results_simulated)
    print(week)
    print(df_player_tournaments_results_simulated)
    total_points = df_player_tournaments_results_simulated.loc[df_player_tournaments_results_simulated['Calculation']==True,'Points'].sum()
    points[week-1] = total_points
    df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[True,week,"No Tournament","",0,0,points[week-1]]
    
    df_week = df_player_tournaments_results_simulated[df_player_tournaments_results_simulated["Week"]==week-1]
    if len(df_week)>0:
        df_week_ranking_simulated.loc[week-2,'Tournament']=df_week['Tournament'].values[0]
        df_week_ranking_simulated.loc[week-2,'Points Earned']=df_week['Points'].values[0]
        
for week in range(max_week+1,53):
    df_week_ranking_simulated.loc[week-1,'Tournament']=df_week_ranking['Tournament'].iloc[week-1]
    df_week_ranking_simulated.loc[week-1,'Points Earned']=df_week_ranking['Points Earned'].iloc[week-1]

# if max_week<52:
#     for week in range(max_week+2,53):
#         points[week-1]=points[week-2]-df_week_ranking['Points to defend'].iloc[week-1]
#         df_week = df_player_tournaments_results_simulated[df_player_tournaments_results_simulated["Week"]==week-1]
#         #Si on a un tournoi sur cette semaine:
#         if len(df_week)>0:
#             #Calcule des points
#             if df_week['Calculation'].iloc[0]==True and week!=1:
#                 points[week-1]=points[week-2]-df_week['Points'].iloc[0]
#             elif df_week['Calculation'].iloc[0]==True and week==1:
#                 points[week-1]=points[week-1]-df_week['Points'].iloc[0]
#             elif week>=2:
#                 points[week-1]=points[week-2]

#             if df_week['Calculation'].iloc[0]==True:
#                 df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],df_week['Points'].iloc[0],points[week-1]]
                
#         elif week>=1:
#             points[week-1]=points[week-2]
#             df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,"No Tournament","",0,0,points[week-1]]

3
    Year  Week                                         Tournament Result  \
0   2022    17                        2022 European Championships    3/4
1   2022    13                               Orleans Masters 2022      1
2   2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
3   2022    44                                     HYLO Open 2022    3/4
4   2022    24                  EAST VENTURES Indonesia Open 2022   9/16
5   2022    12                              YONEX Swiss Open 2022    5/8
6   2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
7   2022    11  YONEX All England Open Badminton Championships...  17/32
8   2023     2                        PETRONAS Malaysia Open 2023  17-32
9   2022    10                    YONEX GAINWARD German Open 2022   9/16
10  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
11  2022    42              Denmark Open 2022 presented by VICTOR  17/32
12  2022    43                             YONEX French Open 2022  17/32
13  2022     4                    DAIHATSU Indonesia Masters 2022  17/32
14  2022    34         TotalEnergies BWF World Championships 2022  33/64

    Points  Calculation                                            Matches  \
0     6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1     5500         True  ../sport/player.aspx?id=A8B53352-A398-4564-BF2...
2     5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
3     4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
4     4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
5     3850         True  ../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
6     3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
7     3000         True  ../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
8     3000         True
9     2750         True  ../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
10    2660        False  ../sport/player.aspx?id=29025589-10CA-4357-906...
11    2660        False  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12    2660        False  ../sport/player.aspx?id=10B084D8-292F-4586-874...
13    2220        False  ../sport/player.aspx?id=F75FB4EC-43FB-4E92-98F...
14    1300        False  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

    Team  Continental Games  Continental Championships  World Championships
0      0                  0                          1                    0
1      0                  0                          0                    0
2      1                  0                          0                    0
3      0                  0                          0                    0
4      0                  0                          0                    0
5      0                  0                          0                    0
6      0                  0                          0                    0
7      0                  0                          0                    0
8      0                  0                          0                    0
9      0                  0                          0                    0
10     0                  0                          0                    0
11     0                  0                          0                    0
12     0                  0                          0                    0
13     0                  0                          0                    0
14     0                  0                          0                    1
4
    Year  Week                                         Tournament Result  \
0   2022    17                        2022 European Championships    3/4
1   2022    13                               Orleans Masters 2022      1
2   2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
3   2022    44                                     HYLO Open 2022    3/4
4   2022    24                  EAST VENTURES Indonesia Open 2022   9/16
5   2022    12                              YONEX Swiss Open 2022    5/8
6   2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
7   2022    11  YONEX All England Open Badminton Championships...  17/32
8   2023     2                        PETRONAS Malaysia Open 2023  17-32
9   2022    10                    YONEX GAINWARD German Open 2022   9/16
10  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
11  2022    42              Denmark Open 2022 presented by VICTOR  17/32
12  2022    43                             YONEX French Open 2022  17/32
13  2022     4                    DAIHATSU Indonesia Masters 2022  17/32
14  2022    34         TotalEnergies BWF World Championships 2022  33/64

    Points  Calculation                                            Matches  \
0     6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1     5500         True  ../sport/player.aspx?id=A8B53352-A398-4564-BF2...
2     5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
3     4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
4     4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
5     3850         True  ../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
6     3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
7     3000         True  ../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
8     3000         True
9     2750         True  ../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
10    2660        False  ../sport/player.aspx?id=29025589-10CA-4357-906...
11    2660        False  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12    2660        False  ../sport/player.aspx?id=10B084D8-292F-4586-874...
13    2220        False  ../sport/player.aspx?id=F75FB4EC-43FB-4E92-98F...
14    1300        False  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

    Team  Continental Games  Continental Championships  World Championships
0      0                  0                          1                    0
1      0                  0                          0                    0
2      1                  0                          0                    0
3      0                  0                          0                    0
4      0                  0                          0                    0
5      0                  0                          0                    0
6      0                  0                          0                    0
7      0                  0                          0                    0
8      0                  0                          0                    0
9      0                  0                          0                    0
10     0                  0                          0                    0
11     0                  0                          0                    0
12     0                  0                          0                    0
13     0                  0                          0                    0
14     0                  0                          0                    1
5
    Year  Week                                         Tournament Result  \
0   2022    17                        2022 European Championships    3/4
1   2022    13                               Orleans Masters 2022      1
2   2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
3   2022    44                                     HYLO Open 2022    3/4
4   2022    24                  EAST VENTURES Indonesia Open 2022   9/16
5   2022    12                              YONEX Swiss Open 2022    5/8
6   2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
7   2022    11  YONEX All England Open Badminton Championships...  17/32
8   2023     2                        PETRONAS Malaysia Open 2023  17-32
9   2022    10                    YONEX GAINWARD German Open 2022   9/16
10  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
11  2022    42              Denmark Open 2022 presented by VICTOR  17/32
12  2022    43                             YONEX French Open 2022  17/32
13  2022    34         TotalEnergies BWF World Championships 2022  33/64

    Points  Calculation                                            Matches  \
0     6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1     5500         True  ../sport/player.aspx?id=A8B53352-A398-4564-BF2...
2     5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
3     4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
4     4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
5     3850         True  ../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
6     3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
7     3000         True  ../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
8     3000         True
9     2750         True  ../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
10    2660        False  ../sport/player.aspx?id=29025589-10CA-4357-906...
11    2660        False  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12    2660        False  ../sport/player.aspx?id=10B084D8-292F-4586-874...
13    1300        False  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

    Team  Continental Games  Continental Championships  World Championships
0      0                  0                          1                    0
1      0                  0                          0                    0
2      1                  0                          0                    0
3      0                  0                          0                    0
4      0                  0                          0                    0
5      0                  0                          0                    0
6      0                  0                          0                    0
7      0                  0                          0                    0
8      0                  0                          0                    0
9      0                  0                          0                    0
10     0                  0                          0                    0
11     0                  0                          0                    0
12     0                  0                          0                    0
13     0                  0                          0                    1
6
    Year  Week                                         Tournament Result  \
0   2022    17                        2022 European Championships    3/4
1   2022    13                               Orleans Masters 2022      1
2   2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
3   2022    44                                     HYLO Open 2022    3/4
4   2022    24                  EAST VENTURES Indonesia Open 2022   9/16
5   2022    12                              YONEX Swiss Open 2022    5/8
6   2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
7   2022    11  YONEX All England Open Badminton Championships...  17/32
8   2023     2                        PETRONAS Malaysia Open 2023  17-32
9   2022    10                    YONEX GAINWARD German Open 2022   9/16
10  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
11  2022    42              Denmark Open 2022 presented by VICTOR  17/32
12  2022    43                             YONEX French Open 2022  17/32
13  2022    34         TotalEnergies BWF World Championships 2022  33/64

    Points  Calculation                                            Matches  \
0     6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1     5500         True  ../sport/player.aspx?id=A8B53352-A398-4564-BF2...
2     5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
3     4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
4     4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
5     3850         True  ../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
6     3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
7     3000         True  ../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
8     3000         True
9     2750         True  ../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
10    2660        False  ../sport/player.aspx?id=29025589-10CA-4357-906...
11    2660        False  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12    2660        False  ../sport/player.aspx?id=10B084D8-292F-4586-874...
13    1300        False  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

    Team  Continental Games  Continental Championships  World Championships
0      0                  0                          1                    0
1      0                  0                          0                    0
2      1                  0                          0                    0
3      0                  0                          0                    0
4      0                  0                          0                    0
5      0                  0                          0                    0
6      0                  0                          0                    0
7      0                  0                          0                    0
8      0                  0                          0                    0
9      0                  0                          0                    0
10     0                  0                          0                    0
11     0                  0                          0                    0
12     0                  0                          0                    0
13     0                  0                          0                    1
7
    Year  Week                                         Tournament Result  \
0   2022    17                        2022 European Championships    3/4
1   2022    13                               Orleans Masters 2022      1
2   2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
3   2022    44                                     HYLO Open 2022    3/4
4   2022    24                  EAST VENTURES Indonesia Open 2022   9/16
5   2022    12                              YONEX Swiss Open 2022    5/8
6   2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
7   2022    11  YONEX All England Open Badminton Championships...  17/32
8   2023     2                        PETRONAS Malaysia Open 2023  17-32
9   2022    10                    YONEX GAINWARD German Open 2022   9/16
10  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
11  2022    42              Denmark Open 2022 presented by VICTOR  17/32
12  2022    43                             YONEX French Open 2022  17/32
13  2022    34         TotalEnergies BWF World Championships 2022  33/64

    Points  Calculation                                            Matches  \
0     6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1     5500         True  ../sport/player.aspx?id=A8B53352-A398-4564-BF2...
2     5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
3     4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
4     4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
5     3850         True  ../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
6     3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
7     3000         True  ../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
8     3000         True
9     2750         True  ../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
10    2660        False  ../sport/player.aspx?id=29025589-10CA-4357-906...
11    2660        False  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12    2660        False  ../sport/player.aspx?id=10B084D8-292F-4586-874...
13    1300        False  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

    Team  Continental Games  Continental Championships  World Championships
0      0                  0                          1                    0
1      0                  0                          0                    0
2      1                  0                          0                    0
3      0                  0                          0                    0
4      0                  0                          0                    0
5      0                  0                          0                    0
6      0                  0                          0                    0
7      0                  0                          0                    0
8      0                  0                          0                    0
9      0                  0                          0                    0
10     0                  0                          0                    0
11     0                  0                          0                    0
12     0                  0                          0                    0
13     0                  0                          0                    1
8
    Year  Week                                         Tournament Result  \
0   2022    17                        2022 European Championships    3/4
1   2022    13                               Orleans Masters 2022      1
2   2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
3   2022    44                                     HYLO Open 2022    3/4
4   2022    24                  EAST VENTURES Indonesia Open 2022   9/16
5   2022    12                              YONEX Swiss Open 2022    5/8
6   2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
7   2022    11  YONEX All England Open Badminton Championships...  17/32
8   2023     2                        PETRONAS Malaysia Open 2023  17-32
9   2022    10                    YONEX GAINWARD German Open 2022   9/16
10  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
11  2022    42              Denmark Open 2022 presented by VICTOR  17/32
12  2022    43                             YONEX French Open 2022  17/32
13  2022    34         TotalEnergies BWF World Championships 2022  33/64

    Points  Calculation                                            Matches  \
0     6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1     5500         True  ../sport/player.aspx?id=A8B53352-A398-4564-BF2...
2     5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
3     4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
4     4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
5     3850         True  ../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...
6     3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
7     3000         True  ../sport/player.aspx?id=1916AA17-D5D3-4EE4-978...
8     3000         True
9     2750         True  ../sport/player.aspx?id=3EE97BA3-95BB-460D-B46...
10    2660        False  ../sport/player.aspx?id=29025589-10CA-4357-906...
11    2660        False  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
12    2660        False  ../sport/player.aspx?id=10B084D8-292F-4586-874...
13    1300        False  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

    Team  Continental Games  Continental Championships  World Championships
0      0                  0                          1                    0
1      0                  0                          0                    0
2      1                  0                          0                    0
3      0                  0                          0                    0
4      0                  0                          0                    0
5      0                  0                          0                    0
6      0                  0                          0                    0
7      0                  0                          0                    0
8      0                  0                          0                    0

17
   Year  Week                                         Tournament Result  \
0  2022    17                        2022 European Championships    3/4
1  2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
2  2022    44                                     HYLO Open 2022    3/4
3  2022    24                  EAST VENTURES Indonesia Open 2022   9/16
4  2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
5  2023     2                        PETRONAS Malaysia Open 2023  17-32
6  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
7  2022    42              Denmark Open 2022 presented by VICTOR  17/32
8  2022    43                             YONEX French Open 2022  17/32
9  2022    34         TotalEnergies BWF World Championships 2022  33/64

   Points  Calculation                                            Matches  \
0    6420         True  ../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...
1    5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
2    4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
3    4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
4    3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
5    3000         True
6    2660         True  ../sport/player.aspx?id=29025589-10CA-4357-906...
7    2660         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
8    2660         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...
9    1300         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

   Team  Continental Games  Continental Championships  World Championships
0     0                  0                          1                    0
1     1                  0                          0                    0
2     0                  0                          0                    0
3     0                  0                          0                    0
4     0                  0                          0                    0
5     0                  0                          0                    0
6     0                  0                          0                    0
7     0                  0                          0                    0
8     0                  0                          0                    0
9     0                  0                          0                    1
18
   Year  Week                                         Tournament Result  \
0  2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
1  2022    44                                     HYLO Open 2022    3/4
2  2022    24                  EAST VENTURES Indonesia Open 2022   9/16
3  2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
4  2023     2                        PETRONAS Malaysia Open 2023  17-32
5  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
6  2022    42              Denmark Open 2022 presented by VICTOR  17/32
7  2022    43                             YONEX French Open 2022  17/32
8  2022    34         TotalEnergies BWF World Championships 2022  33/64

   Points  Calculation                                            Matches  \
0    5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
1    4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
2    4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
3    3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
4    3000         True
5    2660         True  ../sport/player.aspx?id=29025589-10CA-4357-906...
6    2660         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
7    2660         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...
8    1300         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

   Team  Continental Games  Continental Championships  World Championships
0     1                  0                          0                    0
1     0                  0                          0                    0
2     0                  0                          0                    0
3     0                  0                          0                    0
4     0                  0                          0                    0
5     0                  0                          0                    0
6     0                  0                          0                    0
7     0                  0                          0                    0
8     0                  0                          0                    1
19
   Year  Week                                         Tournament Result  \
0  2022    19  TotalEnergies BWF Thomas and Uber Cup Finals 2022      1
1  2022    44                                     HYLO Open 2022    3/4
2  2022    24                  EAST VENTURES Indonesia Open 2022   9/16
3  2022    20          GR TOYOTA GAZOO RACING Thailand Open 2022   9/16
4  2023     2                        PETRONAS Malaysia Open 2023  17-32
5  2022    35                     DAIHATSU YONEX Japan Open 2022  17/32
6  2022    42              Denmark Open 2022 presented by VICTOR  17/32
7  2022    43                             YONEX French Open 2022  17/32
8  2022    34         TotalEnergies BWF World Championships 2022  33/64

   Points  Calculation                                            Matches  \
0    5243         True  ../sport/player.aspx?id=4E68E080-BF68-463C-ACA...
1    4900         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...
2    4800         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...
3    3600         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...
4    3000         True
5    2660         True  ../sport/player.aspx?id=29025589-10CA-4357-906...
6    2660         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...
7    2660         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...
8    1300         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...

   Team  Continental Games  Continental Championships  World Championships
0     1                  0                          0                    0
1     0                  0                          0                    0
2     0                  0                          0                    0
3     0                  0                          0                    0
4     0                  0                          0                    0
5     0                  0                          0                    0
6     0                  0                          0                    0
7     0                  0                          0                    0
8     0                  0                          0                    1
20
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2022    24           EAST VENTURES Indonesia Open 2022   9/16    4800
2  2022    20   GR TOYOTA GAZOO RACING Thailand Open 2022   9/16    3600
3  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
4  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
5  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
6  2022    43                      YONEX French Open 2022  17/32    2660
7  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...     0
2         True  ../sport/player.aspx?id=E16742AE-6672-4B41-8B2...     0
3         True                                                        0
4         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
5         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
6         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
7         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    0
6                  0                          0                    0
7                  0                          0                    1
21
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2022    24           EAST VENTURES Indonesia Open 2022   9/16    4800
2  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
3  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
4  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
5  2022    43                      YONEX French Open 2022  17/32    2660
6  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...     0
2         True                                                        0
3         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
4         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
5         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
6         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    0
6                  0                          0                    1
22
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2022    24           EAST VENTURES Indonesia Open 2022   9/16    4800
2  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
3  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
4  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
5  2022    43                      YONEX French Open 2022  17/32    2660
6  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...     0
2         True                                                        0
3         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
4         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
5         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
6         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    0
6                  0                          0                    1
23
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2022    24           EAST VENTURES Indonesia Open 2022   9/16    4800
2  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
3  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
4  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
5  2022    43                      YONEX French Open 2022  17/32    2660
6  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...     0
2         True                                                        0
3         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
4         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
5         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
6         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    0
6                  0                          0                    1
24
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2022    24           EAST VENTURES Indonesia Open 2022   9/16    4800
2  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
3  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
4  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
5  2022    43                      YONEX French Open 2022  17/32    2660
6  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True  ../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...     0
2         True                                                        0
3         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
4         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
5         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
6         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    0
6                  0                          0                    1
25
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
2  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
3  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
4  2022    43                      YONEX French Open 2022  17/32    2660
5  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
3         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
4         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
5         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    1
26
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
2  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
3  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
4  2022    43                      YONEX French Open 2022  17/32    2660
5  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
3         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
4         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
5         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
4                  0                          0                    0
5                  0                          0                    1
27
   Year  Week                                  Tournament Result  Points  \
0  2022    44                              HYLO Open 2022    3/4    4900
1  2023     2                 PETRONAS Malaysia Open 2023  17-32    3000
2  2022    35              DAIHATSU YONEX Japan Open 2022  17/32    2660
3  2022    42       Denmark Open 2022 presented by VICTOR  17/32    2660
4  2022    43                      YONEX French Open 2022  17/32    2660
5  2022    34  TotalEnergies BWF World Championships 2022  33/64    1300

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=29025589-10CA-4357-906...     0
3         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
4         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0
5         True  ../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0

36
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
37
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
38
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
39
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
40
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
41
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
42
   Year  Week                             Tournament Result  Points  \
0  2022    44                         HYLO Open 2022    3/4    4900
1  2023     2            PETRONAS Malaysia Open 2023  17-32    3000
2  2022    42  Denmark Open 2022 presented by VICTOR  17/32    2660
3  2022    43                 YONEX French Open 2022  17/32    2660

   Calculation                                            Matches  Team  \
0         True  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0
1         True                                                        0
2         True  ../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...     0
3         True  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0

   Continental Games  Continental Championships  World Championships
0                  0                          0                    0
1                  0                          0                    0
2                  0                          0                    0
3                  0                          0                    0
43
   Year  Week                   Tournament Result  Points  Calculation  \
0  2022    44               HYLO Open 2022    3/4    4900         True
1  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True
2  2022    43       YONEX French Open 2022  17/32    2660         True

                                             Matches  Team  Continental Games  \
0  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0                  0
1                                                        0                  0
2  ../sport/player.aspx?id=10B084D8-292F-4586-874...     0                  0

   Continental Championships  World Championships
0                          0                    0
1                          0                    0
2                          0                    0
44
   Year  Week                   Tournament Result  Points  Calculation  \
0  2022    44               HYLO Open 2022    3/4    4900         True
1  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

                                             Matches  Team  Continental Games  \
0  ../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...     0                  0
1                                                        0                  0

   Continental Championships  World Championships
0                          0                    0
1                          0                    0
45
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
46
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
47
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
48
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
49
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
50
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
51
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0
52
   Year  Week                   Tournament Result  Points  Calculation  \
0  2023     2  PETRONAS Malaysia Open 2023  17-32    3000         True

  Matches  Team  Continental Games  Continental Championships  \
0             0                  0                          0

   World Championships
0                    0

In [36]:
df_week_ranking_simulated

,Simulation,Week,Tournament,Result,Points Earned,Points to defend,Total Ranking Points
0,False,1,No Tournament,,0,0,42723
1,False,2,PETRONAS Malaysia Open 2023,,3000,0,42723
2,True,3,No Tournament,,0,0,43063
3,True,4,No Tournament,,0,0,43063
4,True,5,No Tournament,,0,0,43063
5,True,6,No Tournament,,0,0,43063
6,True,7,No Tournament,,0,0,43063
7,True,8,No Tournament,,0,0,43063
8,True,9,No Tournament,,0,0,43063
9,True,10,YONEX GAINWARD German Open 2022,,2750,0,43063
10,True,11,YONEX All England Open Badminton Championships...,,3000,0,42973
11,True,12,YONEX Swiss Open 2022,,3850,0,42633
12,True,13,Orleans Masters 2022,,5500,0,41443
13,True,14,No Tournament,,0,0,37243
14,True,15,No Tournament,,0,0,37243
15,True,16,No Tournament,,0,0,37243
16,True,17,2022 European Championships,,6420,0,37243
17,True,18,No Tournament,,0,0,30823
18,True,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,,5243,0,30823
19,True,20,GR TOYOTA GAZOO RACING Thailand Open 2022,,3600,0,25580
20,True,21,No Tournament,,0,0,21980
21,True,22,No Tournament,,0,0,21980
22,True,23,No Tournament,,0,0,21980
23,True,24,EAST VENTURES Indonesia Open 2022,,4800,0,21980
24,True,25,No Tournament,,0,0,17180
25,True,26,No Tournament,,0,0,17180
26,True,27,No Tournament,,0,0,17180
27,True,28,No Tournament,,0,0,17180
28,True,29,No Tournament,,0,0,17180
29,True,30,No Tournament,,0,0,17180
30,True,31,No Tournament,,0,0,17180
31,True,32,No Tournament,,0,0,17180
32,True,33,No Tournament,,0,0,17180
33,True,34,TotalEnergies BWF World Championships 2022,,1300,0,17180
34,True,35,DAIHATSU YONEX Japan Open 2022,,2660,0,15880
35,True,36,No Tournament,,0,0,13220
36,True,37,No Tournament,,0,0,13220
37,True,38,No Tournament,,0,0,13220
38,True,39,No Tournament,,0,0,13220
39,True,40,No Tournament,,0,0,13220
40,True,41,No Tournament,,0,0,13220
41,True,42,Denmark Open 2022 presented by VICTOR,,2660,0,13220
42,True,43,YONEX French Open 2022,,2660,0,10560
43,True,44,HYLO Open 2022,,4900,0,7900
44,True,45,No Tournament,,0,0,3000
45,True,46,No Tournament,,0,0,3000
46,True,47,No Tournament,,0,0,3000
47,True,48,No Tournament,,0,0,3000
48,True,49,No Tournament,,0,0,3000
49,True,50,No Tournament,,0,0,3000
50,True,51,No Tournament,,0,0,3000
51,True,52,No Tournament,,0,0,3000

In [37]:
custom_data_simulated = np.stack((df_week_ranking_simulated['Tournament'],df_week_ranking_simulated['Result'],df_week_ranking_simulated['Points Earned'],df_week_ranking_simulated['Points to defend']), axis=-1)


fig.add_trace(go.Scatter(x=df_week_ranking_simulated['Week'],
                                y=df_week_ranking_simulated['Total Ranking Points'],
                                customdata=custom_data_simulated,
                                name="Ranking Simulated",
                                marker_color=df_week_ranking_simulated['Points Earned'],
                                marker_colorscale="Plasma",
                                marker_showscale=False,
                                fill="tozerox",
                                fillcolor="rgba(171,219,227,0.2)"))

fig.update_traces(mode="markers+lines",
                    hovertemplate = '<b>Week %{x}:</b>'+
                    '<br><b>Total Ranking Points</b>: %{y}'+
                    '<br>Tournament: %{customdata[0]}'+
                    '<br>Result: %{customdata[1]}'+
                    '<br>Points Earned: %{customdata[2]}'+
                    '<br>Points to Defend: %{customdata[3]}')

fig.show()

In [242]:
df_player_tournaments_results_simulated = get_world_ranking(df_player_tournaments_results_simulated)
total_points = df_player_tournaments_results_simulated.loc[df_player_tournaments_results_simulated['Calculation']==True,'Points'].sum()
df_player_tournaments_results_simulated

5243.0
43913.0

,Year,Week,Tournament,Result,Points,Calculation,Matches,Team,Continental Games,Continental Championships,World Championships
10,2023,2,PETRONAS Malaysia Open 2023,17-32,3000.0,True,,0,0,0,0
11,2023,3,YONEX SUNRISE India Open 2023,17-32,2660.0,False,,0,0,0,0
7,2023,4,DAIHATSU Indonesia Masters 2023,9-16,3600.0,True,,0,0,0,0
5,2023,7,2023 European Mixed Team Championships,1,4707.0,False,,1,0,0,0
15,2023,10,YONEX German Open 2023,17-32,1670.0,False,,0,0,0,0
9,2023,11,YONEX All England Open Badminton Championships...,17-32,3000.0,True,,0,0,0,0
6,2022,12,YONEX Swiss Open 2022,5/8,3850.0,True,../sport/player.aspx?id=8D464DF7-7BD7-43AB-AE1...,0,0,0,0
1,2022,13,Orleans Masters 2022,1,5500.0,True,../sport/player.aspx?id=A8B53352-A398-4564-BF2...,0,0,0,0
0,2022,17,2022 European Championships,3/4,6420.0,True,../sport/player.aspx?id=01ED9B4E-C494-490E-ADD...,0,0,1,0
2,2022,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,1,5243.0,True,../sport/player.aspx?id=4E68E080-BF68-463C-ACA...,1,0,0,0
8,2022,20,GR TOYOTA GAZOO RACING Thailand Open 2022,9/16,3600.0,True,../sport/player.aspx?id=E16742AE-6672-4B41-8B2...,0,0,0,0
4,2022,24,EAST VENTURES Indonesia Open 2022,9/16,4800.0,True,../sport/player.aspx?id=B49D1B9A-A767-4C59-A18...,0,0,0,0
16,2022,34,TotalEnergies BWF World Championships 2022,33/64,1300.0,False,../sport/player.aspx?id=9BC6D676-3D48-4551-BF0...,0,0,0,1
12,2022,35,DAIHATSU YONEX Japan Open 2022,17/32,2660.0,False,../sport/player.aspx?id=29025589-10CA-4357-906...,0,0,0,0
13,2022,42,Denmark Open 2022 presented by VICTOR,17/32,2660.0,False,../sport/player.aspx?id=FD1C4D79-6704-43B7-BB5...,0,0,0,0
14,2022,43,YONEX French Open 2022,17/32,2660.0,False,../sport/player.aspx?id=10B084D8-292F-4586-874...,0,0,0,0
3,2022,44,HYLO Open 2022,3/4,4900.0,True,../sport/player.aspx?id=89EE4B68-4D0F-477B-8FA...,0,0,0,0

In [238]:
df_player_tournaments_results_simulated = df_player_tournaments_results_simulated.sort_values(by=['Week'], ascending=True)

#On va calculer le nombre de points au fur et Ã  mesure des semaines 
points = [0]*53

df_week_ranking_simulated = pd.DataFrame(columns = ['Simulation','Week','Tournament','Result','Points Earned','Points to defend','Total Ranking Points'])

for week in range(0,df_tournament_simulated['Week'].min()):
    points[week] = df_week_ranking['Total Ranking Points'].iloc[week]
    df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,"No Tournament","",0,0,points[week]]
                                                                   
for week in range(df_tournament_simulated['Week'].min(),53):
    df_week = df_player_tournaments_results_simulated[df_player_tournaments_results_simulated["Week"]==week]
    #Si on a un tournoi sur cette semaine:
    if len(df_week)>0:
        #Calcule des points
        if df_week['Calculation'].iloc[0]==True and week!=1:
            if df_week['Year'].iloc[0]==2023:
                points[week]=points[week-1]+df_week['Points'].iloc[0]-df_week_ranking['Points to defend'].iloc[week-2]
            else:
                points[week]=points[week-1]-df_week['Points'].iloc[0]
        elif df_week['Calculation'].iloc[0]==True and week==1:
            if df_week['Year'].iloc[0]==2023:
                points[week]=points[week]+df_week['Points'].iloc[0]-df_week_ranking['Points to defend'].iloc[week-1]
            else:
                points[week]=points[week]-df_week['Points'].iloc[0]
        elif week>=2:
            points[week]=points[week-1]

        if df_week['Calculation'].iloc[0]==True:
            if df_week['Year'].iloc[0]==2023:
                df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[True,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],df_week['Points'].iloc[0],points[week-1]]
            else:
                df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],df_week['Points'].iloc[0],points[week-1]]
        else:
            if df_week['Year'].iloc[0]==2023:
                df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[True,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],0,points[week-1]]
            else:
                df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,df_week['Tournament'].iloc[0],df_week['Result'].iloc[0],df_week['Points'].iloc[0],0,points[week-1]]

    elif week>=1:
        points[week]=points[week-1]

        df_week_ranking_simulated.loc[len(df_week_ranking_simulated)]=[False,week,"No Tournament","",0,0,points[week-1]]


df_week_ranking_simulated

,Simulation,Week,Tournament,Result,Points Earned,Points to defend,Total Ranking Points
0,False,0,No Tournament,,0.0,0.0,42723.0
1,False,1,No Tournament,,0.0,0.0,42723.0
2,True,2,PETRONAS Malaysia Open 2023,17-32,3000.0,3000.0,42723.0
3,True,3,YONEX SUNRISE India Open 2023,17-32,2660.0,0.0,45723.0
4,True,4,DAIHATSU Indonesia Masters 2023,9-16,3600.0,3600.0,45723.0
5,False,5,No Tournament,,0.0,0.0,49323.0
6,False,6,No Tournament,,0.0,0.0,49323.0
7,True,7,2023 European Mixed Team Championships,1,4707.0,0.0,49323.0
8,False,8,No Tournament,,0.0,0.0,49323.0
9,False,9,No Tournament,,0.0,0.0,49323.0
10,True,10,YONEX German Open 2023,17-32,1670.0,0.0,49323.0
11,True,11,YONEX All England Open Badminton Championships...,17-32,3000.0,3000.0,49323.0
12,False,12,YONEX Swiss Open 2022,5/8,3850.0,3850.0,49573.0
13,False,13,Orleans Masters 2022,1,5500.0,5500.0,45723.0
14,False,14,No Tournament,,0.0,0.0,40223.0
15,False,15,No Tournament,,0.0,0.0,40223.0
16,False,16,No Tournament,,0.0,0.0,40223.0
17,False,17,2022 European Championships,3/4,6420.0,6420.0,40223.0
18,False,18,No Tournament,,0.0,0.0,33803.0
19,False,19,TotalEnergies BWF Thomas and Uber Cup Finals 2022,1,5243.0,5243.0,33803.0
20,False,20,GR TOYOTA GAZOO RACING Thailand Open 2022,9/16,3600.0,3600.0,28560.0
21,False,21,No Tournament,,0.0,0.0,24960.0
22,False,22,No Tournament,,0.0,0.0,24960.0
23,False,23,No Tournament,,0.0,0.0,24960.0
24,False,24,EAST VENTURES Indonesia Open 2022,9/16,4800.0,4800.0,24960.0
25,False,25,No Tournament,,0.0,0.0,20160.0
26,False,26,No Tournament,,0.0,0.0,20160.0
27,False,27,No Tournament,,0.0,0.0,20160.0
28,False,28,No Tournament,,0.0,0.0,20160.0
29,False,29,No Tournament,,0.0,0.0,20160.0
30,False,30,No Tournament,,0.0,0.0,20160.0
31,False,31,No Tournament,,0.0,0.0,20160.0
32,False,32,No Tournament,,0.0,0.0,20160.0
33,False,33,No Tournament,,0.0,0.0,20160.0
34,False,34,TotalEnergies BWF World Championships 2022,33/64,1300.0,0.0,20160.0
35,False,35,DAIHATSU YONEX Japan Open 2022,17/32,2660.0,0.0,20160.0
36,False,36,No Tournament,,0.0,0.0,20160.0
37,False,37,No Tournament,,0.0,0.0,20160.0
38,False,38,No Tournament,,0.0,0.0,20160.0
39,False,39,No Tournament,,0.0,0.0,20160.0
40,False,40,No Tournament,,0.0,0.0,20160.0
41,False,41,No Tournament,,0.0,0.0,20160.0
42,False,42,Denmark Open 2022 presented by VICTOR,17/32,2660.0,0.0,20160.0
43,False,43,YONEX French Open 2022,17/32,2660.0,0.0,20160.0
44,False,44,HYLO Open 2022,3/4,4900.0,4900.0,20160.0
45,False,45,No Tournament,,0.0,0.0,15260.0
46,False,46,No Tournament,,0.0,0.0,15260.0
47,False,47,No Tournament,,0.0,0.0,15260.0
48,False,48,No Tournament,,0.0,0.0,15260.0
49,False,49,No Tournament,,0.0,0.0,15260.0
50,False,50,No Tournament,,0.0,0.0,15260.0
51,False,51,No Tournament,,0.0,0.0,15260.0
52,False,52,No Tournament,,0.0,0.0,15260.0

In [239]:
custom_data_simulated = np.stack((df_week_ranking_simulated['Tournament'],df_week_ranking_simulated['Result'],df_week_ranking_simulated['Points Earned'],df_week_ranking_simulated['Points to defend']), axis=-1)


fig.add_trace(go.Scatter(x=df_week_ranking_simulated['Week'],
                                y=df_week_ranking_simulated['Total Ranking Points'],
                                customdata=custom_data_simulated,
                                name="Ranking Simulated",
                                marker_color=df_week_ranking_simulated['Points Earned'],
                                marker_colorscale="Plasma",
                                marker_showscale=False,
                                fill="tozerox",
                                fillcolor="rgba(171,219,227,0.2)"))

fig.update_traces(mode="markers+lines",
                    hovertemplate = '<b>Week %{x}:</b>'+
                    '<br><b>Total Ranking Points</b>: %{y}'+
                    '<br>Tournament: %{customdata[0]}'+
                    '<br>Result: %{customdata[1]}'+
                    '<br>Points Earned: %{customdata[2]}'+
                    '<br>Points to Defend: %{customdata[3]}')

fig.show()

In [4]:
df_estimation_ranking = pd.read_excel("./averaged_points_ranking_all.xlsx",['men_singles','women_singles','men_doubles','women_doubles','mixed_doubles'])

In [13]:
df_estimation_ranking = df_estimation_ranking['men_singles']

KeyError: 'men_singles'

In [14]:
df_estimation_ranking

     year  Rank   mean_points
0    2018     1  89669.792453
1    2018     2  82965.679245
2    2018     3  79996.245283
3    2018     4  77057.188679
4    2018     5  73808.226415
..    ...   ...           ...
795  2023   196   6971.769231
796  2023   197   6948.615385
797  2023   198   6911.538462
798  2023   199   6874.692308
799  2023   200   6821.230769

[800 rows x 3 columns]

In [12]:
list_ranking = df_estimation_ranking.groupby('Rank')['mean_points'].mean().values

In [11]:
list_ranking[100]

16785.9156083696

In [32]:
df_estimation_ranking_grouped = pd.DataFrame(columns=['Top','High Points','Low Points'])
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 5",list_ranking[0],list_ranking[4]]
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 6-10",list_ranking[5],list_ranking[9]]
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 11-20",list_ranking[10],list_ranking[19]]
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 21-32",list_ranking[20],list_ranking[31]]
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 33-50",list_ranking[32],list_ranking[49]]
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 51-100",list_ranking[50],list_ranking[99]]
df_estimation_ranking_grouped.loc[len(df_estimation_ranking_grouped)] = ["Top 101-200",list_ranking[100],list_ranking[199]]

In [33]:
df_estimation_ranking_grouped

           Top    High Points    Low Points
0        Top 5  101077.830145  73675.985464
1     Top 6-10   70408.791276  58938.720601
2    Top 11-20   57742.529506  46005.239843
3    Top 21-32   44990.743543  36423.290039
4    Top 33-50   35523.944729  25769.978845
5   Top 51-100   25379.301004  12703.027246
6  Top 101-200   12570.254299   5414.040331

In [51]:
total_points = 24643.0
closest_value = min(list_ranking, key=lambda x:abs(x-total_points))
ranking = (np.where(list_ranking == closest_value)[0]+1)[0]
print(ranking)

53

In [8]:
df_estimation_ranking.groupby('Rank')['mean_points'].mean()

AttributeError: 'dict' object has no attribute 'groupby'

In [42]:
url_world_ranking = 'https://bwf.tournamentsoftware.com/ranking/ranking.aspx?rid=70'

df_options_weeks = pd.DataFrame(columns=['options_weeks','weeks_ids'])

source = urllib.request.urlopen(url_world_ranking).read()
soup = bs.BeautifulSoup(source,'lxml')

ranking_week = soup.find('select')
weeks = ranking_week.find_all('option')

for option in weeks:
    if option.text.strip().split('/')[2]=='2023':
        df_options_weeks.loc[len(df_options_weeks)]=[option.text.strip(),option['value'].strip()]

df_options_weeks['weeks_ids'] = df_options_weeks['weeks_ids'].astype('int')
df_options_weeks = df_options_weeks.sort_values(by=['weeks_ids'], ascending=True)
df_options_weeks['weeks_ids'] = df_options_weeks['weeks_ids'].astype('str')
df_options_weeks.reset_index(drop=True,inplace=True)

df_options_weeks

   options_weeks weeks_ids
0       1/3/2023     32857
1      1/10/2023     32945
2      1/17/2023     33023
3      1/24/2023     33087
4      1/31/2023     33201
5       2/7/2023     33278
6      2/14/2023     33362
7      2/21/2023     33436
8      2/28/2023     33537
9       3/7/2023     33633
10     3/14/2023     33731
11     3/21/2023     33802
12     3/28/2023     33883

In [43]:
details_week = df_options_weeks[df_options_weeks['options_weeks']=="1/3/2023"]

In [46]:
details_week.index[0]

0